### ISSUE TITLE
Mixed arguments

### ISSUE THREAD

**Issue by edmBernard** [yargs/yargs#1006]
With this yargs code: 
```node
var argv = require('yargs')
    .option('port', {
        type: 'number', demand: true, nargs: 1, default: 8080
    })
    .option('address', {
        type: 'string', demand: true, nargs: 1, default: "localhost"
    })
    .option('password', {
        type: 'string', nargs: 1
    })
    .alias('h', 'help')
    .argv;

console.log(argv)
```
In the following situation, yargs was not able to output error and mixed arguments:
```bash
./app.js --port --password 123456 --address 192.168.0.1
{ _: [ 123456 ],
  help: false,
  h: false,
  version: false,
  port: NaN,
  address: '192.168.0.1',
  '$0': 'app.js',
  password: undefined }
```

Maybe something is wrong in my code, Is there a way to avoid that ?
Is there a way to block arguments with "--" to be parse by others ?

**Comment by edmBernard** [comment]
ok I failed in my code with the rigth options the error is correct:
```node
var argv = require('yargs')
    .option('port', {
        type: 'number', demand: true, requiresArg: true, default: 6379
    })
    .option('address', {
        type: 'string', demand: true, requiresArg: true, default: "localhost"
    })
    .option('password', {
        type: 'string', requiresArg: true
    })
    .alias('h', 'help')
    .version("0.0.1")
    .argv;
```

but still  strange behavior with `nargs`

**Comment by bcoe** [comment]
@edmBernard this behavior with nargs seems a bit weird, but is _kind of_ what I'd expect. Because you had port configured with `nargs: 1`, it will try to consume at lease one argument after its declaration. In the case of your example code, I believe it consumed the `--password` field, which it then parsed as `NaN` (since you have it configured as a number).

Feel free to open a new issue if you have any specific edge-cases around `narg` you'd like to report.
