### ISSUE TITLE
Order of positional and option

### ISSUE THREAD

**Issue by Nautigsam** [yargs/yargs#1044]
I have this code that sets a positional and an option inside a command context:
```javascript
// test.js
const program = require('yargs')

const argv = program(process.argv.slice(2))
        .demandCommand(1)
        .command({
                command: 'com <pos>',
                desc: 'A command',
                builder: yargs => yargs.positional('pos', {describe: 'A positional'}).option('opt')
        })
        .argv

console.log(argv)
```

When I call the script like this `node test.js com pos --opt`, it works properly, but when I change the order of the option and the positional like this `node test.js com --opt pos`, I get this error:

`Not enough non-option arguments: got 0, need at least 1`

From my experience of other CLI systems, the order of positional and options should not matter.

**Comment by nexdrew** [comment]
Since you have not defined a type for the `opt` option, it thinks `--opt pos` means you want to set the value of `opt` to `pos`. If `opt` is meant to be a boolean option, then try setting the type in one of the following ways:

1. Via the [`option` method](http://yargs.js.org/docs/#api-optionkey-opt)

    ```js
    .option('opt', { type: 'boolean' })
    ```

2. Via the [`boolean` method](http://yargs.js.org/docs/#api-booleankey)

    ```js
    .boolean('opt')
    ```

I personally prefer the `option` method because it lets you define multiple properties for a single option/flag all at once, without having to duplicate the key definition across multiple method calls.

Give this a shot and let us know if it solves your problem or not. Thanks!

**Comment by Nautigsam** [comment]
It worked! Thank you for the hint.
