### ISSUE TITLE
Implicit type detection of default value

### ISSUE THREAD

**Issue by vmx** [yargs/yargs#1063]
What do you think of having implicit type detecting if a default value is given.

Example:

```javascript
const argv = require('yargs')
  .option('verbose', {
    default: true
  })
  .argv
console.log(argv)
```

Running it will output (as expected):
```javascript
{ _: [],
  help: false,
  version: false,
  verbose: true,
  '$0': 'noboolean.js' }
```

But if you want to set `verbose` to `false` it only works with `--no-verbose`. If you run it with `--verbose=false` the output is:
```javascript
{ _: [],
  help: false,
  version: false,
  verbose: 'false',
  '$0': 'noboolean.js' }
```

`verbose` is a string. I would expect it to be a boolean.

To fix this, you need to explicitly set `type` to `boolean`:
```javascript
const argv = require('yargs')
  .option('verbose', {
    default: true,
    type: 'boolean'
  })
  .argv
console.log(argv)
```

Then the output is as expected, the value of `verbose` is a boolean:
```javascript
{ _: [],
  help: false,
  version: false,
  verbose: false,
  '$0': 'simple.js' }
```

If I specify a default value, I implicitly expect that things are parsed the same way as the type the default value has.

I'd be happy to work on a patch.

**Comment by shadowspawn** [comment]
Interesting suggestion, thanks for the detailed description. I am intrigued but this has not got upvoted in the intervening period, and would be a breaking change, so safer to leave as is.

This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
