### ISSUE TITLE
Boolean arguments shouldn't accept values

### ISSUE THREAD

**Issue by Richie765** [yargs/yargs#1077]
A boolean parameter can accept any value, e.g. `--boolean=value` as the doc says:

```
Interpret key as a boolean. If a non-flag option follows key in process.argv, that string won’t get set as the value of key.
```

But I think it doesn't make sense and it's inconsistent. Also, the argument _is_ set as it's value but only if it is 'true'. For instance:

```
--boolean -> true
--boolean=value -> false
--boolean value -> false and value passed as positional
--boolean=true -> true
--boolean true -> true
--boolean=1 -> false
-b true -> true
-b false -> false
-b value -> false and value is seen as positional
```

I think if a superfluous value is passed, that is likely a usage error and should be reported as an error. To make it consistent I think it's best to always treat non-option values as positional arguments if they follow a boolean.

**Comment by plroebuck** [comment]
Yeah, some of these are wrong given the documentation for [`.boolean()`](https://github.com/yargs/yargs/blob/master/docs/api.md#booleankey) and
reasonable user expectations.

```javascript
#!/usr/bin/env node
'use strict';

var _ = require('lodash');
var argv = require('yargs')
  .options({
    'boolean': {
      alias: 'b',
      description: 'Some boolean flag',
      type: 'boolean'
    }
  })
  .argv;

console.log(_.pick(argv, '_', 'boolean', 'b'));
```

```bash
$ bin/testme 
{ _: [], boolean: false, b: false }          # as expected default (false)
$ bin/testme --boolean
{ _: [], boolean: true, b: true }            # as expected (implicit)
$ bin/testme --boolean=true
{ _: [], boolean: true, b: true }            # as expected (explicit)
$ bin/testme --no-boolean
{ _: [], boolean: false, b: false }          # as expected (implicit)
$ bin/testme --boolean=false
{ _: [], boolean: false, b: false }          # as expected (explicit)
$ bin/testme --boolean=foo
{ _: [], boolean: false, b: false }          # fail: expected throw illegal argument
$ bin/testme --boolean true
{ _: [], boolean: true, b: true }            # fail: expected default (false) and _:['true']
$ bin/testme --boolean false
{ _: [], boolean: false, b: false }          # fail: expected _:['false']
$ bin/testme --boolean foo
{ _: [ 'foo' ], boolean: true, b: true }     # as expected
$ bin/testme -b true
{ _: [], boolean: true, b: true }            # fail: expected _:['true']
$ bin/testme -b false
{ _: [], boolean: false, b: false }          # fail: expected _:['false']
$ bin/testme -b foo
{ _: [ 'foo' ], boolean: true, b: true }     # as expected
$ bin/testme --boolean=1
{ _: [], boolean: false, b: false }          # fail: expected throw illegal argument?
$ bin/testme --boolean=TRUE
{ _: [], boolean: false, b: false }          # fail: expected throw illegal argument?
$ bin/testme --boolean --no-boolean
{ _: [], boolean: false, b: false }          # as expected (order options given)
$ bin/testme --no-boolean --boolean
{ _: [], boolean: true, b: true }            # as expected (order options given)
```

Here, I'm assuming that since `--boolean=[true|false]` both give English expected answers (rather than Javascript "truthy" variants), there's some hardcoded comparison going on. Was unsure whether to expect `--boolean=1` to get translated to `true` (both `[0|1]` reasonably could be). 

It would be nice to have a `.mutually_exclusive(key, ...)` method (a la Python's [argparse](https://docs.python.org/2/library/argparse.html#mutual-exclusion)) that could be applied for boolean options to make the last two test cases throw illegal argument.

**Comment by plroebuck** [comment]
> It would be nice to have a `.mutually_exclusive(key, ...)` method (a la Python's [argparse](https://docs.python.org/2/library/argparse.html#mutual-exclusion)) that could be applied for boolean options to make the last two test cases throw illegal argument.

Tried using `.implies()` which looks like it should handle this without success.
```coffee
argv = yargs
  .options(Abao.options)
  .implies({
    'bail': '--no-bail',
    'generate-hooks': '--no-generate-hooks',
    'hooks-only': '--no-hooks-only',
    'invert': '--no-invert',
    'names': '--no-names',
    'reporters': '--no-reporters',
    'sorted': '--no-sorted',
    'template': 'generate-hooks'
  })
  .argv
```

Appeared one of yargs [unit tests](https://github.com/yargs/yargs/blob/master/test/validation.js) was doing something similar, but didn't work for me...

**Comment by bcoe** [comment]
@Richie765 @plroebuck if you don't mind, let's open this discussion on [yargs-parser](https://github.com/yargs/yargs-parser) rather than yargs.

It's always been the behavior of boolean that you can provide a `false` or `true` string, and that providing something other than these accepted values is undefined behavior (defaulting to `false` in most cases for this undefined behavior seems pretty reasonable to me). I'm certainly willing to have a discussion about changing this behavior mind you.
