### ISSUE TITLE
Customize yargs' output

### ISSUE THREAD

**Issue by ifisidro** [yargs/yargs#1084]
Hi everybody,

In our project some members would like to have a different output format than the given by **yargs**. Both for the command (our binary) without arguments and for a command without the proper arguments, we would like to have a different output.

Kind regards,

**Comment by shadowspawn** [comment]
`.showHelpOnFail` displays the help then the error, which might be useful.

This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
