### ISSUE TITLE
--help show commands with $0 included

### ISSUE THREAD

**Issue by rocketspacer** [yargs/yargs#1107]
Code (index.js):
```javascript
#!/usr/bin/env node

const program = require('yargs')
  .command('hello', 'Hello World')
  .argv;
```
Run:
```sh
node index.js --help
```
Expect:
```sh
index.js [command]

Commands:
  hello  Hello World

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]
```
Got:
```sh
index.js [command]

Commands:
  index.js hello  Hello World

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]
```

Node Version: 9.11.1
Yargs Version: 11.0.0

![image](https://user-images.githubusercontent.com/17026876/39052863-977c6512-44d7-11e8-94fd-2e34a8d96710.png)

**Comment by jails** [comment]
This behavior has been introduced in all `>=10.0.0` versions (probably by https://github.com/yargs/yargs/pull/990) so as a workaround I'm just sticking back to `9.0.1`.

**Comment by bcoe** [comment]
you can now use the method [`scriptName`](https://github.com/yargs/yargs/pull/1143) (which will be released soon) to control the name of your script -- giving you a bit more control over the program name displayed in front of commands. 

the reason for the script name prefixing a command is to disambiguate the difference between sub-commands and the top-level command of your application (if you're using `.usage`, or a default command):

```
Commands:
  test.js a              first sub command
  test.js b              second sub command
  test.js <port>     start the application server                      [default]
```

I think the prefix is reasonable, otherwise documenting the syntax of the top-level command becomes difficult.

Give @laggingreflex's `scriptName` method a shot, it will let you truncate the `.js` on the script name, which a few folks have requested.
