### ISSUE TITLE
Can a command be required by default and not required if some option is present?

### ISSUE THREAD

**Issue by jjoselv** [yargs/yargs#1146]
The desired functionality =>
`cli.js import my-id`
Result:
`Importing my-id`

`cli.js import`
Result (as if the ID was required):
`Must provide an id`

`cli.js import --list`
Result:
`List of available imports: my-id, my-id2`

Thanks!

**Comment by Linard11** [comment]
If I understand you right, you don't want the command to be required/not-required, but a positional for it?

So that:
`my-app import <ID>`

but 
`my-app import --list`
will not throw an error that ID is required.

The only thing I can think of right now is to make the ID positional optional, is to do a manual check with check() to throw if it wasn't specified and --list wasn't either, imitating the error yargs would throw.
```
yargs.command('import', 'Import ids',
    yargs => {
        yargs.positional('ID' {
            type: 'number',
            description: 'the id to import',
        });
        yargs.option('list', {
           type: 'boolean',
           description: 'List available ids', 
        });
        yargs.check(argv => {
            if(!argv.list && argv.ID) {
                throw 'Not enough non-option arguments: got 0, need at least 1';
            }
        }
    },
    argv => {
        if (argv.list) {
            console.log('List of available imports...');
        }
    }
);
```

**Comment by jjoselv** [comment]
Ok! I though I was missing an api command or something that does that.

Thanks a lot, I'll use that! 👍
