### ISSUE TITLE
Redirecting help/version output

### ISSUE THREAD

**Issue by haykam821** [yargs/yargs#1149]
I am trying to use Yargs in a non-TTY environment, yet using the `help` subcommand, `--help` option, and `--version` option will only print it to console and exit. I have tried my own implementation:

```js
yargs.command("help", "Shows help for a command.", {}, argv => {
    const helpText = yargs.getUsageInstance().help();
    argv.send(helpText);
});
```

However, this only shows help with that command. How could I make it work so that the output is redirected to my `argv.send` function and the process not exit?

**Comment by cspotcode** [comment]
I think yargs should allow us to dependency-inject the `console` object, just like it allows for the `argv` array.  It can also provide a 'string' option for convenience, where all output goes to a string.  Something like `yargs.output`

**Comment by Slapbox** [comment]
Any news on this?

When we print output from `--help` or `--version` in an Electron app seems to crash the process, but no other argument is affected and it doesn't seem to affect apps that doesn't use `yargs` (though I haven't tested that extensively yet.)

I wonder if it's related to this, since other commands don't cause an issue.

**Comment by bcoe** [comment]
@Slapbox @haykam821 yargs now has a method `.getHelp()` which you can use to create the output string:

https://github.com/yargs/yargs/blob/main/docs/api.md#gethelp

You can alternatively provide a callback to the `parse()` method, which will be passed the output from yargs:

https://github.com/yargs/yargs/blob/main/docs/api.md#parseargs-context-parsecallback
