### ISSUE TITLE
Dependency question

### ISSUE THREAD

**Issue by swedebugia** [yargs/yargs#1263]
Which dependencies are needed for:
Building? Excluding linting, testing, minifying

**Comment by shadowspawn** [comment]
This is an old request. The answer isn't something that will be stable, or that npm/yarn/etc support as such. If you are still interested, could you give more context around why you are asking?

This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.

**Comment by shadowspawn** [comment]
Just saw #1250 which has more explanation! (I won't close that one.)
