### ISSUE TITLE
.strict() allows extra args

### ISSUE THREAD

**Issue by stefk** [yargs/yargs#1313]
Documentation states that in strict mode, extra arguments are reported as errors. However, none of the constructs allowed by yargs seems to demonstrate that behaviour. For example, the following configs:

```js
require("yargs")
  .command("foo <bar>")
  .strict()
  .argv
```
```js
require("yargs")
  .command("foo <bar>", "foo cmd", yargs => yargs.strict())
  .strict()
  .argv
```
```js
require("yargs")
  .command({
    command: "foo <bar>",
    builder: yargs => yargs.strict()
  })
  .command({
    command: "baz <qux>",
    builder: yargs => yargs.strict()
  })
  .demandCommand()
  .strict()
  .argv;
```
all result in commands like

```
$ ./cmd foo 123 extra
$ ./cmd bar 456 extra-1 extra-2
```

being accepted without any error.

**Comment by OJezu** [comment]
Considering how buggy and unpredictable positional arguments are, this might be a feature...

**Comment by coreyfarrell** [comment]
In nyc I worked around this by calling `yargs.demandCommand(0, 0)` in the command builders.

**Comment by bcoe** [comment]
@stefk thank you for the bug report 👍 would happily accept a patch for this behavior.

**Comment by bcoe** [comment]
@stefk @coreyfarrell this should now be fixed if you run `npm i yargs@next`, let me know if it does the trick for you and I'll promote the release soon?

**Comment by stefk** [comment]
@bcoe, I've just tested and everything works fine now. Thanks!

**Comment by coreyfarrell** [comment]
I don't think I can test `yargs.strict` in nyc currently due to the way that this restricts results in configuration files.  This becomes a problem where nyc accepts more/less options for certain commands but those options could be in the config file.  In the future if we want to actually use `.strict` I think we would need to restructure so all options are global but some are hidden in command for which they don't apply.

Without testing this one question I have is how would this support enabling `.strict` on the main nyc command, for example `nyc --all mocha mocha-args`.  Specifically how to have yargs verify options like `--all` without blocking sub-process arguments.

**Comment by bcoe** [comment]
@coreyfarrell your issues are unrelated to this change I believe?

We could potentially add a configuration option that allows strict to be disabled for config objects, want to start a separate thread (it might be worth checking if one exists already, I remember discussing this before).

**Comment by coreyfarrell** [comment]
The issue with configuration is unrelated.  The bigger issue comes from the fact that `.strict()` blocks the 'subprocess' arguments.  If the main `yargs` has both subcommands `.command()` and `.strict()` this blocks the main yargs command from supporting subprocess arguments.  So lets assume we don't have any nyc configuration, adding `.strict()` to nyc's main yargs setup would break everything.  Specifically `nyc mocha test/*.js` would through an error due to the unknown arguments `mocha` and `test/*.js`.

This behavior seems a bit inconsistent, take the following:
```js
const {argv} = require('yargs')
  .command(commandObject)
  .strict()
```
The combination of `.command` and `.strict` on the top-level yargs object seem to make it impossible to support a sub-process + arguments.  Removing `.strict()` or removing all `.command()` options seems allow sub-process + arguments to be accepted.

**Comment by OJezu** [comment]
@coreyfarrell Yeah, that deleted comment of mine about strict and arguments being buggy, so extra args was a "feature", was due to this behaviour. I did not provide examples, because of #1324 I had to not use commands altogether.
