### ISSUE TITLE
Add an Ethereum name or address to package.json

### ISSUE THREAD

**Issue by lastmjs** [yargs/yargs#1416]
I would like to see an Ethereum name or address added to the ethereum field of the package.json file. This will allow consumers of the project to know a canonical address to send funds to. For example, I'm building an application that will allow developers to automatically donate ETH to all of their npm dependencies that have an Ethereum address in their package.json file. 

Having an Ethereum address would allow various cryptocurrencies to be donated, including stablecoins pegged to USD, like USDC or DAI. Essentially it is another payment network like PayPal, but open and decentralized like the internet. Getting an address is relatively straightforward through something like MetaMask or Coinbase. You could also generate one on your own.

**Comment by bcoe** [comment]
this sounds like an interesting experiment, are there any platforms that are doing this in practice?

**Comment by lastmjs** [comment]
None that I know of for cryptocurrency. My project is the only one experimenting in this way that I know of. npm may be coming out with a similar concept very soon, though I doubt it will be crypto-focused: https://blog.npmjs.org/post/187382017885/supporting-open-source-maintainers

**Comment by shadowspawn** [comment]
I appreciate that there is a chicken-and-egg problem here with package support vs tooling support, but I don't think this is something that Yargs will adopt in isolation, not least because Yargs does not seek any funding currently. I see you have a repo to gather support for support in "funding": https://github.com/lastmjs/enable-cryptocurrency-in-funding-yml

Full disclosure: I turned this down for Commander too! https://github.com/tj/commander.js/issues/1031

This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
