### ISSUE TITLE
`halt-at-non-option` doesn't work as expected in subcommands

### ISSUE THREAD

**Issue by forivall** [yargs/yargs#1417]
https://github.com/yargs/yargs-parser/pull/181 would also solve my problem

Basically, all of the options are ignored when `halt-at-non-option` is used in a subcommand, and all parsing is halted.

**Comment by bcoe** [comment]
@forivall could you try:

```
npm i yargs@next
```

It has @henderea's changes 🎉

**Comment by zimtsui** [comment]
@bcoe for yargs/yargs-parser#181, i don't think it's a good practice to separate options by whether the option is unknown. but it should be by position.

for example, node has options separated into node-args and script-args by position.

in command `node --experimental-json-modules ./index.js --port=3000`, the `--experimental-json-modules` is recognized to be a node-arg because it appears in front of the first positional argument `./index.js`, and the `--port=3000` is recognized to be a script-arg because it appears behind the first positional argument `./index.js`.

if option "port" were known by both node and the script, and node separated options by whether an option is unknown, then the "port" would be treated as an node-arg.

so, for yargs, the best way is to apply "halt-at-non-option" to subcommands

**Comment by henderea** [comment]
Honestly, the ability to distinguish between defined options and unknown options is very important for me. And it’s a behavior I’m used to coming over from Ruby where the option parsing extracts the options you define and leaves the rest of the arguments. The functionality is behind a setting, so people don’t have to use it if they don’t want. It’s not like the behavior I added is enabled by default.

**Comment by bcoe** [comment]
@henderea @zimtsu might be good to bring the  conversation to a new open issue, with examples? odds are I'll  forget about comments made on a closed issue.
