### ISSUE TITLE
commandDir does not work with TS, part 2

### ISSUE THREAD

**Issue by rulatir** [yargs/yargs#1525]
This is distinct from #1067.

With a workaround similar to mentioned there already applied:

```typescript
    yargs.commandDir('app/commands',{
        extensions: ['js','ts']
    }).demandCommand().argv;
```

```
Error: ENOENT: no such file or directory, scandir '/home/me/works/terratool/file:/home/me/works/terratool/dist/app/commands'
    at Object.readdirSync (fs.js:887:3)
    at requireDirectory (/home/me/works/terratool/node_modules/require-directory/index.js:59:6)
    at Object.addDirectory (/home/me/works/terratool/node_modules/yargs/lib/command.js:112:33)
    at Object.Yargs.self.commandDir (/home/me/works/terratool/node_modules/yargs/yargs.js:379:13)
    at main (file:///home/me/works/terratool/dist/terratool.js:3:11)
    at file:///home/me/works/terratool/dist/terratool.js:8:11
    at file:///home/me/works/terratool/dist/terratool.js:12:5
    at ModuleJob.run (internal/modules/esm/module_job.js:110:37)
    at async Loader.import (internal/modules/esm/loader.js:141:24) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/home/me/works/terratool/file:/home/me/works/terratool/dist/app/commands'
}
```

**Comment by alexcochran** [comment]
What was your eventual solution for this? I'm having the same issue and can't figure out anything about what is going on.

**Comment by rulatir** [comment]
Gave up on yargs in favor of Microsoft's solution.

**Comment by alexcochran** [comment]
I understand that. I went the [oclif](https://oclif.io/) route myself.

**Comment by flisboac** [comment]
I'm using Yargs 17, and I can assure you that TypeScript works, but you need to do some extra configuration, and be wary of some gotchas.

When distributing, I opted to run `tsconfig-replace-paths` on the generated `js` files to replace imports with whatever was configured in my `compilerOptions.paths` config. This eliminates relative paths, and allows me to keep the same file hierarchy between `js` and `ts`. I can then run them the same way both in development and run-time. Of course, that only works if using `outDir`; needless to say, webpack and the like are out of the question, or will be cumbersome to implement if using `commandDir`.

An example `tsconfig.json` (considering all your source code live in the `src` folder, and imported paths also start with `src/`):

```json
{
  "compilerOptions": {
    "target": "es2017",
    "module": "commonjs",
    "moduleResolution": "node",
    "declaration": true,
    "declarationMap": true,
    "inlineSourceMap": true,
    "rootDir": "./",
    "outDir": "./dist/main",
    "baseUrl": ".",
    "paths": {
      "src/*": [
        "src/*"
      ]
    }
  },
  "exclude": [
    "node_modules",
    "build",
    "dist"
  ],
  "include": [
    "src"
  ]
}
```

You can either transpile your script and commands to JavaScript and run them with `node` as usual, or call them as follows (especially useful during development):

```sh
# Supposing you have typescript, ts-node and tsconfig-paths installed
# Can also prefix everything with e.g. npx, but tsconfig-paths still needs to be installed
ts-node -r tsconfig-paths/register my-script.ts
```

Also, I've ran into some problems when specifying `.ts` extensions in `commandDir`, because it also finds and tries to require `.d.ts`. If you emit definition files, be sure to pass in a proper `exclude` configuration on your `commandDir`, e.g.:

```ts
yargs
  .commandDir('app/commands',{
      extensions: ['js','ts'],
      exclude: /.d.ts$/,
  })
  .demandCommand()
  .argv;
```
