### ISSUE TITLE
Customize types 

### ISSUE THREAD

**Issue by EdsonAlcala** [yargs/yargs#1712]
Is there a way to customise the types? i.e in Typescript is common or at least I do very often.

```
type Seconds = number
```
I guess my idea is that it helps to communicate better the program. 

Would it be possible to put aliases for types?

Another thing would be to override the type being shown in the right size? ([number])

<img width="1180" alt="Screenshot 2020-08-07 at 19 37 56" src="https://user-images.githubusercontent.com/3077635/89677945-374b9780-d8e6-11ea-89e1-c91bd6b5f077.png">

Can I hide it? And if I can hide it then it would be nice to declare something like:

```
.option("deadline <seconds>", {
    type: "number",
    demandOption: true,
    describe: "Time limit for x thing",
 })
```

Maybe another option for it?

Thanks a lot !

**Comment by bcoe** [comment]
@EdsonAlcala we're currently trying to delegate support for TypeScript to the `@types/yargs`, so yargs itself doesn't have any real concept of types. 

Are you asking for the ability to provide the type `Seconds` rather than `number`? I don't know if this is possible, but you might start a conversation with the folks working on [`@types/yargs`](https://github.com/DefinitelyTyped/DefinitelyTyped).

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
