### ISSUE TITLE
demand() ignores anything after `--`

### ISSUE THREAD

**Issue by cspotcode** [yargs/yargs#1732]
Here's an example:
https://runkit.com/cspotcode/5f4fe1f3c5d0c8001a637b54

```
some-cli --arrayOption foo bar -- positional1 positional2
```
With:
```
.demand(2)
.array('arrayOption')
```

Complains: "Not enough non-option arguments: got 0, need at least 2"

An array option accepts multiple values.  So to separate it from the demanded positionals, we use `--`.
`demand()` ignores all values after `--`.  Removing `demand()` shows that the values are `--` are parsed correctly and included in the `_` array.

Does `demand`'s deprecation mean this cannot be fixed?

**Comment by bcoe** [comment]
@cspotcode I conceptually think of keys after `--` as meaning, "this is no longer parsing, please stop applying parsing rules and validation to them"

I feel like this is really a problem with implicit arrays, which are a feature I don't love; since they create ambiguity between positionals and array arguments.

If I could do it over, I think I'd suggest writing the above more like this:

```
some-cli --arrayOption foo --arrayOption bar positional1 positional2
```

Where each member of  the array is explicit. And `--` is only used in the cases where you need  to actually break out of the parse.

**Comment by bcoe** [comment]
There's a setting called "greedy arrays" which I'd like to eventually consider defaulting to `false`:

https://github.com/yargs/yargs-parser#greedy-arrays

**Comment by cspotcode** [comment]
These comments aren't addressing the bug raised by this ticket.

**Comment by bcoe** [comment]
@cspotcode I suppose what I'm getting at is that, is that I feel this potentially falls in the category of relying on undocumented  behavior, and I  don't really want to enshrine the behavior,  if I can convince you not to use the `array` type like  this.

**Comment by cspotcode** [comment]
It affects YousefED/typescript-json-schema#362, so it's not actually my code that's using arrays.

The behavior also crops up without using arrays, so it's pretty clearly a bug.

```
cli-that-processes-files -- -annoyingfilenamecomingfromsomewherewedonotcontrol-.txt outputfile.txt
```

The filename could also be the same as a flag or option, and then you'd want `--` to separate positionals.

**Comment by bcoe** [comment]
@cspotcode so the argument is that, if you're collecting positionals after `--` in the `_` variable; they should count towards the `demand(N)` quota?

Is the behavior the same for `demandCommand` of  curiosity?
