### ISSUE TITLE
Trigger commands manually

### ISSUE THREAD

**Issue by LiranBri** [yargs/yargs#1785]
Hi,
Given that my CLI has two commands A, B

can I trigger B from A's handler ?
currently I was able to do so by using [execa](https://github.com/sindresorhus/execa) but if there is a built in way would be better.

**Comment by shadowspawn** [comment]
There is not a built-in way to do this, so up to your code.

This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
