### ISSUE TITLE
Typescript example doesn't compile

### ISSUE THREAD

**Issue by MikeYermolayev** [yargs/yargs#1953]
Hello,

I'm trying to use yargs with typescript but receive errors even after copying code from the docs.

The interesting part is that it starts to work after I `await` for result of argv.

![image](https://user-images.githubusercontent.com/8783498/119830065-8fe73200-bf04-11eb-871c-2fba95078e3b.png)

Here is the text of error:

```
Element implicitly has an 'any' type because expression of type '"a"' can't be used to index type '{ [x: string]: unknown; a: boolean; b: string; c: number | undefined; d: (string | number)[] | undefined; e: number; f: string | undefined; _: (string | number)[]; $0: string; } | Promise<{ [x: string]: unknown; a: boolean; b: string; c: number | undefined; ... 4 more ...; $0: string; }>'.
  Property 'a' does not exist on type '{ [x: string]: unknown; a: boolean; b: string; c: number | undefined; d: (string | number)[] | undefined; e: number; f: string | undefined; _: (string | number)[]; $0: string; } | Promise<{ [x: string]: unknown; a: boolean; b: string; c: number | undefined; ... 4 more ...; $0: string; }>'
```

Here is my tsconfig:
```json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "commonjs",
    "strict": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "outDir": "dist",
    "lib": ["ESNext"]
  },
  "include": ["./src/**/*"]
}

```
I'm using: 
```
"@types/yargs": "^17.0.0",
"yargs": "^17.0.1"
```

Thanks in advance

**Comment by karizma** [comment]
As you can see from the error, the type of argv is a union. The first item is the arguments and the second one is a promise which resolves to those arguments. That is why when you await it, it gets the correct type.

The reason it's a union is because in yargs you can have commands, and the handlers for those commands can be asynchronous. And so `.argv` would resolve after that command finishes.

In the example, you aren't using any asynchronous commands, but yargs typing doesn't know that when you are just calling `.argv` or `.parse`.

What you need to do is use [#parseSync](https://yargs.js.org/docs/#api-reference-parsesyncargs-context-parsecallback) which explicitally tells yargs you have no asynchronous commands (this will also throw errors if there are async commands).

```js
#!/usr/bin/env node
import yargs = require('yargs/yargs');

const argv = yargs(process.argv.slice(2)).options({
  a: { type: 'boolean', default: false },
  b: { type: 'string', demandOption: true },
  c: { type: 'number', alias: 'chill' },
  d: { type: 'array' },
  e: { type: 'count' },
  f: { choices: ['1', '2', '3'] }
}).parseSync();

argv.b // no error
```

![code](https://user-images.githubusercontent.com/48662020/120255231-18d9d280-c251-11eb-9ba9-dbe9d1b3573e.png)

**Comment by mafo5** [comment]
Thanks. Exactly what I am looking for. Should be in the documentation!

**Comment by tobystaines** [comment]
I have been having the same issue (+1 to add this to the docs), but when I add `.parseSync()` I get the error "TypeError: yargs_1.default(...).options(...).parseSync is not a function"

**Comment by karizma** [comment]
@tobystaines what versions of `@types/yargs` and yargs do you have?

**Comment by bluelovers** [comment]
a demo for how make argv to sync like old day

```ts
type IUnPackArgv<T extends Argv<any>> = T extends Argv<infer O> ? O : never;

type IArgvSync<T> = Omit<Argv<T>, 'argv'> & {
	argv: {
		[key in keyof Arguments<T>]: Arguments<T>[key]
	}
}

export function setupToYargs<T>(yargs: Argv<T>)
{
	const _return = yargs
		.option('preset', {
			desc: `Name of the preset you want to use. Must be one of the following:\n@bluelovers/conventional-changelog-bluelovers, angular, atom, codemirror, ember, eslint, express, jquery, jscs or jshint`,
			alias: ['p', 'changelogPreset'],
			string: true,
		})
		.option('lerna-package', {
			desc: `Generate a changelog for a specific lerna package (:pkg-name@1.0.0)`,
			alias: 'l',
			boolean: true,
			default: true,
		})
		.option('type', {
			string: true,
		})
		.option('tag-prefix', {
			desc: `Tag prefix to consider when reading the tags`,
			alias: 't',
			string: true,
		})
		.option('cwd', {
			default: process.cwd(),
			normalize: true,
		})
	;

	return _return as IArgvSync<IUnPackArgv<typeof _return>>
}
```

**Comment by tobystaines** [comment]
> @tobystaines what versions of `@types/yargs` and yargs do you have?

@karizma 17.0.0 (and yargs 17.0.1, ts-node 10.0.0/node 14.16.1)

**Comment by Whobeu** [comment]
Thanks! This was driving me crazy. I have several Typescript projects using yargs. Some were suddenly throwing new errors with argv properties like noted in this issue. Others were still fine. I even tried putting some of the problematic modules into a directory where modules were not having problems and they were fine there. Finally discovered the "good' directories were still on yargs 16.2.0 as I somehow forgot to upgrade them and npm was reporting otherwise. When I upgraded them to 17.0.1, they started throwing errors too. I found this issue here and parseSync() solved the problem.
