### ISSUE TITLE
How to theme/style/color the help output of a command?

### ISSUE THREAD

**Issue by davidfirst** [yargs/yargs#1956]
I would like to have the command description as green and the flags/options as blue. 
Is there an option to do it?

Thanks!

**Comment by karizma** [comment]
I don't think there is currently an api to do so. You can use `.help(false)`, a middleware function and a custom fail function to get control of the help output, but you will need to find a way to retrieve the description and options. Replacing the options is pretty easy since they are prefixed with either -- or -, but descriptions and positional options will take more work.

```js
function logHelp(help) {
	console.log(help.replace(/(--|-)([\w-]+)/g, `$1${chalk.blueBright('$2')}`));
}

const parser = yargs(process.argv.slice(2))
	.command({ ... })
	.command({ ... })
	.help(false)
	.fail((msg, err, innerYargs) => {
		if (err) {
			throw err;
		}

		innerYargs.showHelp(logHelp);
		console.log('\n' + msg);
		process.exit(0);
	})
	.scriptName("monkey")
	.strict();

parser.middleware((innerArgv) => {
	if (innerArgv.help || innerArgv.h) {
		parser.showHelp(logHelp);
		process.exit(0);
	}
}, true);

// call the parser
parser.argv;
```
![image](https://user-images.githubusercontent.com/48662020/120370291-05bf1500-c2da-11eb-908c-648180e4ed89.png)

**Comment by karizma** [comment]
This could be a feature request though, maybe have a method that takes in modifiers for any of the text:

```js
yargs.modifyHelp({
    command: (str) => str,
    positionalOptions: (str) => str,
    shorthandOptions: (str) => str,
    longhandOptionName: (str) => str,
    commandDescription: (str) => str
    // ...
});
```

Although I don't think it should be a priority since most people don't use colors for cli help output.

**Comment by davidfirst** [comment]
@karizma , thanks!
Almost there. The problem with the regex above is that every word that starts with `-` or `--` is colored. I have such occurrences in the descriptions. 
I tested it and besides the issue above, it seems to be working. Thanks!

Ideally, would be an API that I can re-format the options only.

**Comment by karizma** [comment]
I've tried a couple things with regex and I don't know if it's possible with regex alone. 
The next solution would be just putting a limit on how many times a line can be replaced. But I don't think there's a built in way 
to do that with javascript, and def not a way to specify that limit is for each line.

So instead I just split the help message line by line, and then if a line is an option it replaces it with the regex before, and uses a custom replacer function.

```js
function logHelp(help) {
	let replacedAmount = 0;

	function replacer(match, p1, p2) {
		if (replacedAmount === 2) {
			return match;
		}

		replacedAmount++;
		return `${p1}${chalk.blueBright(p2)}`;
	}

	const lines = help.split('\n');
	let passedOptions = false;

	for (let i = 0; i < lines.length; i++) {
		const line = lines[i];

		if (line.startsWith('Options:')) {
			passedOptions = true;
		} else if (passedOptions) {
			lines[i] = line.replace(/(--|-)([\w-]+)/g, replacer);
			replacedAmount = 0;
		}
	}

	console.log(lines.join('\n'));
}
```

This gives more customization for the future as well. But this is prob gonna be really slow.

Worth noting previously I called `process.exit(0)` inside of `.fail()`, you should prob change the status code to 1 since it is an error.

Last inside the regex, the part that captures the description is: `[\w-]+`, if you have any non word characters inside of them you need to add it to the range.

**Comment by davidfirst** [comment]
@karizma , thanks for you help! I really appreciate it.
I continued your work and replaced this:
```
lines[i] = line.replace(/(--|-)([\w-]+)/g, replacer);
```
with
```
lines[i] = line.replace(/(--)([\w-]+)/, replacer).replace(/(-)([\w-]+)/, replacer);
```
so it doesn't replace all, only one occurrence of `--` and one occurrence of `-`. 
It seems to be fine for the most cases. I'll have an issue when an option doesn't have an alias and has `-` in the description. but it's good enough.

Thanks again!

**Comment by karizma** [comment]
> I'll have an issue when an option doesn't have an alias and has - in the description. but it's good enough.

For your `-` regex you can use `^\s+` so it only captures it if the lines starts with it. But this only works if your options are in the format of: `-s, --silent` it will fail if they are `--silent, -s` (I'm pretty sure yargs doesn't even output options like this so it should be fine).

If you plan on using replace twice, you don't need a replacer function, and you don't need to capture the `--` or `-`.

```js
lines[i] = line
	.replace(/--([\w-]+)/, `--${chalk.blueBright('$1')}`)
	.replace(/^(\s+)-(\w)/, `$1-${chalk.blueBright('$2')}`);
```

Another bug is when you only have a single letter alias but no long form of it. Example: having `-s` for silent but not `--silent`.

Last bug I know of would be if you had an alias that wasn't only one letter, like `--log-equation` and `--log`, It wouldn't color the second one. But I'm guessing you already know that.  If you do want to be able to have an alias that's not only one letter, you will need to modify the first regex and probably add a replacer function.

Tried to solve them but my regex just gets messy, and I'm not even sure if you will run into those problems since it depends on your cli style.

> thanks for you help! I really appreciate it.

No problem, glad I could help.

**Comment by shadowspawn** [comment]
An answer was provided (thanks @kitesi and @davidfirst), and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
