### ISSUE TITLE
Use Yargs synchronously in class constructor

### ISSUE THREAD

**Issue by ixuz** [yargs/yargs#2175]
Can Yargs be used to parse cli and environment variables synchronously in a constructor?

For example calling using `yargs.argv['hello'],` in a typescript may cause the following error:

```
Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{
  [x: string]: unknown;
  _: (string | number)[];
  $0: string;
} | Promise<{
  [x: string]: unknown;
  _: (string | number)[];
  $0: string;
}>'.

No index signature with a parameter of type 'string' was found on type '{
  [x: string]: unknown;
  _: (string | number)[];
  $0: string;
} | Promise<{
  [x: string]: unknown;
  _: (string | number)[];
  $0: string;
}>'.ts(7053)
```

This issue was also discussed in [error TS7053: Element implicitly has an 'any' type because expression + other TS errors](https://stackoverflow.com/questions/67781743/error-ts7053-element-implicitly-has-an-any-type-because-expression-other-ts)

Under what conditions can the `yargs.argv` be a promise rather than just a plain old object?

**Comment by jesec** [comment]
Yeah. The typing is clearly erroneous. 

`{...} | Promise` means the code below (the user of the `argv`) has to handle BOTH the promise case and the non-promise (synchronous) case. It makes things extremely difficult and essentially makes `await` mandatory. 

- Suppose `argv` **is** a Promise. I can't use `then` with this typing because the typing declares that it **might NOT** be a Promise. `error: Property 'then' does not exist on type ....`.
- Vice versa, suppose `argv` **is NOT** a Promise. I can't use any of the properties because the typing declares that it **might** be a Promise. `Property '...' does not exist on type 'Promise<...`

The situation is the worst in both cases. This is a critical issue for TypeScript users. As for the solution, we can either split the async/sync function (maybe restore `yargs` to sync-only  for backwards compat and add `yargsAsync`?). Alternatively, there might be a way to write the typing so the types can be correctly inferred.

**Comment by nwalters512** [comment]
Especially for folks using versions of Node that don't support top-level await (or folks using CJS instead of ESM), it's pretty unergonomic to shoehorn async/await code into something that was previously just a synchronous script.

For anyone looking for an alternative to yargs, https://www.npmjs.com/package/commander is a great option. It defaults to synchronous parsing and has a separate `parseAsync()` function that works well with TypeScript.

**Comment by bcoe** [comment]
Yargs has a separate `parse` and `parseAsync` method now.
