### ISSUE TITLE
global options should be completion

### ISSUE THREAD

**Issue by atian25** [yargs/yargs#2182]
```js
yargs(hideBin(process.argv))
  .command({
    command: 'test',
    description: 'test command',
    builder: {
      json: {
        description: 'output json',
        type: 'boolean',
        default: false,
      }
    }
  })
  .options({
    registry: {
      description: 'remote registry url',
    },
  })
  .help()
  .completion()
  .argv;
```

but:

<img width="240" alt="image" src="https://user-images.githubusercontent.com/227713/167245883-d01eeba4-7498-4db9-b9f3-89ebdbae9e4d.png">

**Comment by jly36963** [comment]
## Reproduction

### Steps

- I created `~/example.js`
- I ran `~/example.js completion`
- I copied output to `~/.zshrc`
- added execute permission to `~/example.js`

I then tested completion for `cmd1`, `cmd2`, `opt1`, and `verbose` -- all worked as I expected 

`example.js cmd1 --verb [press tab]` resulted in `example.js cmd1 --verbose`

### Script

```js
#! /usr/local/bin/node
const yargs = require('yargs')

const input = process.argv.slice(2)

yargs(input)
  .command(
    'cmd1',
    'cmd1 desc',
    yargs => yargs.option('opt1', { desc: 'opt1 desc', type: 'string' }),
    argv => console.log(argv)
  )
  .command(
    'cmd2',
    'cmd2 desc',
    yargs => yargs.option('opt1', { desc: 'opt1 desc', type: 'string' }),
    argv => console.log(argv)
  )
  .option('verbose', { desc: 'verbose desc', type: 'boolean' })
  .completion()
  .parse()
```

I tried it with `argv` instead of `.parse()`, as well as `options()` instead of `option()`. It worked for each scenario

### Context

I'm using Mac, zsh, node 17.3.1, and yargs 17.4.1 (current master branch)

## Questions

Can you provide the following?
- Yargs version
- Node version
- Platform (more specifically, if you're using zsh or bash)

It seemed to work for me, am I missing something?

**Comment by edukisto** [comment]
@jly36963’s solution works in Ubuntu 20.04, too.

The only change I made is to replace `#!/usr/local/bin/node` with `#!/usr/bin/env node` to make the script compatible with [NVM](https://github.com/nvm-sh/nvm).

GNU bash v5.0.17.

Node.js v12, v14, v16, v18.

yargs v17.4.1.

**Comment by shadowspawn** [comment]
An answer was provided (thanks @jly36963 and @edukisto), and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
