### ISSUE TITLE
yargs treats quoted value that begins -- as an argument

### ISSUE THREAD

**Issue by rcoundon** [yargs/yargs#2266]
The following code, when called with:
```shell
./app.js test stage '--hello' 
```

Returns the error:
```shell
Unknown argument: hello
``` 

```js
#!/usr/bin/env node
const yargs = require('yargs/yargs')
const { hideBin } = require('yargs/helpers')

const program = yargs(hideBin(process.argv))
  .scriptName("test")
  .option("stage", {
    type: "string",
  })
  .demandCommand(1)
  .strict()
  .parseSync()

console.log(program._)
```

It seems that, even if a value is quoted, yargs still matches it as an argument if it starts --

I can't say a way to configure yargs to parse the quoted value as a string and not treat the -- specially.

The use case here was a command line utility that receives a private key definition that begins `-----BEGIN RSA PRIVATE KEY-----`

**Comment by shadowspawn** [comment]
The quoting on the command-line affects how the shell parses the command-line, but the quotes get removed before node and then yargs get a chance to see them.

Try logging `process.argv` to see what yargs is working with.

A few ideas for possible approaches:
- make the key an option, and specify the value with `=` like `--private-key="$MY_PRIVATE_KEY"`
- read the key from a file instead of on the command-line
- if there is an earlier non-option argument, turn on `halt-at-non-option` in https://github.com/yargs/yargs-parser

**Comment by bcoe** [comment]
@rcoundon could you share the exact input you're giving from the command line, as a gist?

**Comment by rcoundon** [comment]
I'm not building directly with yargs, it's being used as part of the [sst](https://github.com/serverless-stack/sst/) package
However, my recreation looks like [this](https://gist.github.com/rcoundon/809e46a4dace96862a2dfead9d6e5a58)

**Comment by rcoundon** [comment]
FYI - setting the parserConfiguration option
`'unknown-options-as-args': true,` does seem to fix, or at least workaround, the issue

**Comment by bcoe** [comment]
@rcoundon I'm glad you found a solution that works for you 👍
