### ISSUE TITLE
Won't trigger any code for any command

### ISSUE THREAD

**Issue by zigomi** [yargs/yargs#2347]
I have this:

    import yargs from "yargs";
    import { hideBin } from 'yargs/helpers';

      //....
      yargs(hideBin(process.argv)).command('--add-item <val1> <val2>', 'desc', {},
          async (argv) => {
            const { val1, val2 } = argv;
            if (val1 && val2) {
              /**/
            } else {
              console.log('Wrong command line arguments');
            }
        })
        .command('--print <val1>', 'description 123', {},
          async (argv) => {
            const { val1 } = argv;
            if (val1) {
                /**/
            } else {
               console.log('Wrong command line arguments');
            }
        })
        .demandCommand(1, 'You need to provide at least one command')
        .help()
        .alias('help', 'h')
        .parse();
        //......

Then I'll run it:

    $ node my_script.js --add-item 1 2
    // or
    // $ node my_script.js --print 33

And will always get:

    my_script.js <command>

    Commands:
    my_script.js --add-item <val1> <val2>
    // ...........

That is, it'll show the help info; none of the commands will get triggered.

What's the matter? 

If I remove 2 dashes:

    .command('add-item <val1> <val2>', 'desc', {},

Yet, it won't work:

     $ node my_script.js add-item --val1 3 --val2 55
     // or 
     // $ node my_script.js add-item  3  55

===>

      (1) Not enough non-option arguments: got 0, need at least 2
      (2) (silence)

**Comment by zigomi** [comment]
version 17.x

**Comment by shadowspawn** [comment]
Also posted on Stack Overflow: https://stackoverflow.com/questions/76733603/yargs-wont-trigger-any-command-of-a-script

**Comment by zigomi** [comment]
@shadowspawn this is also no less relevant that your link to my own question:

![92SF_1__29544](https://github.com/yargs/yargs/assets/89519556/7d7b7ed6-1049-48bc-9572-86dbdbf3aaf5)

**Comment by shadowspawn** [comment]
Is a picture of a spade relevant because you are digging into a solution? (joke)

A link to other places you have asked the same question is relevant to people with a similar question. There may be answers there.

A link to other places you have asked the same question is relevant to people who might answer it. Perhaps it has already been answered well and no point wasting time writing up the same information. Perhaps the person asking the question is no longer interested in an answer, so the focus here could be on future visitors to this issue.

**Comment by shadowspawn** [comment]
> What's the matter?
> `.command('--add-item <val1> <val2>'`

Options are recognised by two `--` in front for long options like `--example`, or one dash in front and a single letter like `-e`. So `--add-item` does not work as the name of a command because it gets parsed as an option.

For historical interest, you can actually use options like commands in your own code, but it is not modern syntax. `tar` is an example of an old program with "modes" written before subcommands became common.

```
% tar --help
tar(bsdtar): manipulate archive files
First option must be a mode specifier:
  -c Create  -r Add/Replace  -t List  -u Update  -x Extract
```

**Comment by shadowspawn** [comment]
> If I remove 2 dashes:
> (2) $ node my_script.js add-item  3  55
> (2) (silence)

In your example code you do not produce any output when `add-item` is called correctly. (You may have had some in your real program.)

It is working for me with this simplified example:

```js
// index.mjs
import yargs from "yargs/yargs";
import { hideBin } from 'yargs/helpers';

yargs(hideBin(process.argv)).command('add-item <val1> <val2>', 'desc', {},
    async (argv) => {
       console.log('Called add-item')
       console.log(argv)
    })
    .demandCommand(1, 'You need to provide at least one command')
    .parse();
```

```console
% node index.mjs add-item one two
Called add-item
{ _: [ 'add-item' ], '$0': 'index.mjs', val1: 'one', val2: 'two' }
```

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
