### ISSUE TITLE
Bash completion:  Long vs short options and number of dashes

### ISSUE THREAD

**Issue by jhenninger** [yargs/yargs#265]
When using the bash completion feature, yargs completes short options with two
leading dashes instead of just one:

test.js:

``` javascript
var argv = require('yargs')
  .alias('l', 'long')
  .describe('l', 'an option')
  .help('h')
  .alias('h', 'help')
  .completion('completion')
  .argv;

console.log(argv);
```

```
$ node test.js --get-yargs-completions
--l
--h
```

This isn't a huge issue because using the double-dashed short options still works:

```
$ node test.js --l foo
{ _: [],
  h: false,
  help: false,
  l: 'foo',
  long: 'foo',
  '$0': 'test.js' }
```

But I think it would be much better to always use the long options for completions, as they are generally more descriptive. If a long option is not available it should fall back to the single-dashed short version.

**Comment by bcoe** [comment]
this still appears to be a bug, if anyone happens to see this issue, would very much appreciate help addressing some bugs with our bash completion logic.

**Comment by mleguen** [comment]
@jhenninger 's issue is reproducible now using:

```bash
$ node test.js --get-yargs-completions node test.js -
--version
--l
--h
```

So if understand well, 2 issues are to be addressed here:
# if a long option is available, it should be displayed instead of the short one
# if only a short option is available, it should be displayed with a single dash

The first issue can already be adressed by defining the long option as the real option name, and the short one as an alias, as yarg's option completion does not seem to take aliases into account. So changing the code to:

```js
var argv = require('yargs')
  .alias('long', 'l')
  .describe('long', 'an option')
  .help('help')
  .alias('help', 'h')
  .completion('completion')
  .argv;

console.log(argv);
```

will complete with long options:

```bash
$ node test.js --get-yargs-completions node test.js -
--version
--long
--help
```

The second point is still to be adressed by showing only one dash when the option name is only one character long (and not a digit).
