### ISSUE TITLE
yargs.commands as yargs.options

### ISSUE THREAD

**Issue by paazmaya** [yargs/yargs#288]
Allow defining multiple commands in an object, in the same manner as via `.options` (as oppose to `.option`).

It might make #174 easier

**Comment by nexdrew** [comment]
@paazmaya Thanks for the suggestion! See [similar discussion here](https://github.com/bcoe/yargs/issues/225#issuecomment-129289198) and let us know what you think.

**Comment by bcoe** [comment]
Ultimately (since 2015) we ended up introducing the concept of loading commands from folders, which I think ends up being a nice abstraction if folks want to define tons of commands.

I'd like to avoid adding an additional `.commands` flag; my goal these days being to make an effort to reduce yargs' overall API surface.
