### ISSUE TITLE
Positional fallbacks

### ISSUE THREAD

**Issue by MadLittleMods** [yargs/yargs#402]
Is there a way to specify a fallback value for a named parameter as a positional parameter?

With `nomnom`, this is accomplished with [`opts.position`](https://www.npmjs.com/package/nomnom#position). Having it as an alias `opts.alias: 0` could work nicely but isn't exactly backwards compatible.

Currently you can get similar functionality with `yargs` but requires some extra logic:

`ban.js`

``` js
#!/usr/bin/env node
var yargs = require('yargs');


var argv = yargs.argv;
var shimPosition = function(optionsOpts) {
  var opts = Object.assign({}, optionsOpts);

  if(opts.hasOwnProperty('position') && opts.position < argv._.length) {
    opts.default = opts.default || argv._[opts.position];
  }

  return opts;
}


var argv = yargs
  .option('username', shimPosition({
    position: 0,
    required: true,
  }))
 .option('unban', {
    type: 'boolean',
    alias: 'u',
    description: 'Whether to unban the user'
  })
  .argv;

console.log(argv);
```

[_`shimPosition` source_](https://gist.github.com/MadLittleMods/018089c00bc9e0852112e5740cfc9a5c)

`ban.js foo`
`ban.js --username=foo`
`ban.js foo -u`
`ban.js --username=foo -u`

**Comment by nexdrew** [comment]
@MadLittleMods Thanks!

The support for positional arguments is very limited at the moment and only applies to commands, where positional args are defined in the command string.

- To define a required positional arg, use a command string like: `ban <username>`

    **Note** that yargs does not currently support passing a required positional arg with a flag on the command line.

- To define an optional positional arg, use a command string like: `ban [username]`

    You can pass these as flagless args or flagged options on the command line.

Note that the former is somewhat equivalent to defining an option as `demand: true`, while the latter allows you to define a default value if the arg is not given via `default: 'some value'`.

I'm not quite sure if you're asking how to apply a default/fallback value to a positional arg, or if you're asking how to make a positional arg required, but as long as you use a command for your "ban" example, you can pretty much accomplish what you want this way:

```js
var argv = require('yargs')
  .command(
    'ban [username]',
    'Ban or unban a user',
    {
      username: {
        type: 'string',
        default: 'unknown'
      },
      u: {
        alias: 'unban',
        type: 'boolean',
        description: 'Whether to unban the user'
      }
    },
    (argv) => {
      console.log('username:', argv.username)
      console.log('unban:', argv.unban)
    }
  )
  .help().alias('h', 'help')
  .argv
```

```
$ ./issue402.js ban foo
username: foo
unban: false

$ ./issue402.js ban --username=foo
username: foo
unban: false

$ ./issue402.js ban foo -u        
username: foo
unban: true

$ ./issue402.js ban --username=foo -u
username: foo
unban: true
```

This is not ideal and we still have a long way to go to make positional args a first-class citizen within yargs, but it's a start.

Just FYI, I think any (additional) support we build for positional args should be name/key-based rather than index-based. I'd rather treat them like standard configurable options - just ones that don't require a flag on the command line.

Let me know what you think.

**Comment by nexdrew** [comment]
Without using a command, here's another form of your workaround using a custon `.check()` function:

```js
var argv = require('yargs')
  .option('_', {
    type: 'string'
  })
  .option('username', {
    type: 'string'
  })
  .option('unban', {
    alias: 'u',
    type: 'boolean',
    description: 'Whether to unban the user'
  })
  .check((argv) => {
    if (argv._.length < 1 && !argv.username) throw new Error('Please specify a username')
    if (!argv.username) argv.username = argv._[0]
    return true
  })
  .help().alias('h', 'help')
  .argv
console.log('username:', argv.username)
console.log('unban:', argv.unban)
```

```
$ ./issue402.js foo
username: foo
unban: false

$ ./issue402.js --username=foo
username: foo
unban: false

$ ./issue402.js --username=foo -u
username: foo
unban: true

$ ./issue402.js foo -u           
username: foo
unban: true
```

**Comment by MadLittleMods** [comment]
Thanks @nexdrew, the custom` .check()` function is another alternative that could work but the first reply involving a custom command doesn't really apply to my use case if I understand it right.

My goal is just to have a named-hyphenated-parameter but if it isn't supplied, use the first a positional arg.

**Comment by bcoe** [comment]
based partially on this conversation (which I unfortunately never updated) we now have the concept of positional arguments which can be described:

https://github.com/yargs/yargs/blob/master/docs/advanced.md#describing-positional-arguments

You can use this in conjunction with default commands, and I think address all the feature requests in this thread 👍 

@MadLittleMods thanks for helping contribute to the design process.

**Comment by MadLittleMods** [comment]
Thanks for the follow-up @bcoe :+1:
