### ISSUE TITLE
how should checks behave for nested commands?

### ISSUE THREAD

**Issue by Enet4** [yargs/yargs#403]
Considering this particular use case:

``` javascript
var argv = require('yargs')
    .command('hunt')
    .boolean('cat')
    .boolean('dog')
    .check(function(argv, opt) {
        // can't take both!
        return !(argv.cat && argv.dog);
    })
    .argv;

console.log(argv);
```

Running it with the arguments `--cat --dog` alone will trigger the check and fail to proceed, as expected. However, when running with `hunt --cat --dog`, the check function isn't called at all. One could argue that I can just specify the check inside the command's builder, but these options apply to all commands, and I wouldn't want to create builders and replicate calls to `check(fn)` to each one of them just for this purpose.

Shouldn't a `check` like this one apply to any (or no) command by default? Otherwise, can we have a means of specifying that the check is global?

**Comment by maxrimue** [comment]
I can confirm this bug. Interestingly, this works with yargs v3, but not with yargs v4.

**Comment by maxrimue** [comment]
I've identified the issue here as follows:
When the `index.js` asks `command.js` for which commands have handler functions ([L619](https://github.com/yargs/yargs/blob/master/index.js#L619)), `command.js` returns all registered commands ([L48](https://github.com/yargs/yargs/blob/master/lib/command.js#L48)), disregarding whether they have handlers or not, which then causes the `index.js` to just run the handler function and not perform any further checks like custom `.check()`'s ([L681](https://github.com/yargs/yargs/blob/master/index.js#L681)).

I will try to find out how to solve this quickly. Thanks for reporting!

**Comment by bcoe** [comment]
@maxrimue @Enet4 with the new approach to command handling here is what my expectation would be:

```js
var argv = require('yargs')
    .command('hunt', 'hunt command', function (yargs) {
      return yargs
        .check(check)
    })
    .boolean('cat')
    .boolean('dog')
    .check(check)
    .argv;

function check () {
  // can't take both!
  return !(argv.cat && argv.dog);
}

console.log(argv);
```

This new command API has the advantage that it's explicit. If we did want different behavior for `hunt` we'd simply not apply the `check`.

I could see an argument being made for `check` being made global ... but I think this might be a bit presumptuous do you have any thoughts @nexdrew?

**Comment by bcoe** [comment]
@jamesr73 @maxrimue let's use this thread to hash out how `check` should behave when nesting commands: does it default to being global? perhaps it's overridden by inner checks?

**Comment by nexdrew** [comment]
I think, in general, a custom top-level check will validate global options, so it probably makes sense to apply it globally, but I don't know if we should make that the default. Either way, the API should make it easy to enable/disable global application.

Would be cool if we could somehow detect which options it wants to validate and apply the function globally if all the options are global.

My question is should we allow for a different check to be applied at each level, such that yargs calls each one that applies, starting at top-level and moving down to (sub)commands - as opposed to just overriding? I could see value in this.

It's almost like we need to map a check to a group of options.

**Comment by nexdrew** [comment]
I'm probably complicating things. Seems easy enough to apply or chain checks manually. I dunno.

**Comment by jamesr73** [comment]
@bcoe @nexdrew @maxrimue 

I think the example where the check function is defined separately is probably the cleanest and most flexible. I've been heading down that route since I noted #408 (different check function for each command, calling out to a common function to check the globals).

The implication there would be that the outer check fires only when the hunt command isn't executed and only the hunt check fires when the hunt command is executed?

**Comment by maxrimue** [comment]
@jamesr73 @nexdrew @bcoe Yep. I think it's probably better to leave `.check()` as it is right now, not being global. Assuming that different commands have different options, it makes more sense to also have different checks. Actually, if I look at some yargs@3 code I wrote some time ago, I also only defined checks within commands, rather than globally, I think that just makes it more explicit.

I would still though note in the readme that `.check()` is not global, if we leave it as it is.

**Comment by Enet4** [comment]
> I would still though note in the readme that .check() is not global, if we leave it as it is.

Indeed, that would be the most important part of this issue's resolution. I created the issue in the first place because the outcome of this particular use case wasn't clear in the documentation. As long as it's clear that checks are command-specific (and that non-command-scoped checks do not propagate to commands), we can call this solved.

**Comment by fearphage** [comment]
I'm not sure exactly where this left off. Is `check` currently not usable by subcommands?

I tried the following:

```js
exports.check = function(argv) {
  return argv.foo && argv.bar;
}
```

It's currently not being called. Is it only supported globally?

**Comment by nexdrew** [comment]
@fearphage Custom checks should indeed be defined per-(sub)command, it's just that yargs doesn't look for a `check` property of a command module. Rather, you should define this in the `builder` function of the command, like so:

```js
module.exports = {
  command: 'tryit',
  desc: 'This is my super helpful description',
  builder: function (yargs) {
    yargs.option('foo', {
      desc: 'foo for thought',
      type: 'string'
    }).option('bar', {
      desc: 'a dog and a cat walk into a bar...',
      type: 'string'
    }).check(function (argv) {
      return Boolean(argv.foo && argv.bar)
    })
  },
  handler: function (argv) {
    console.log(`do something with foo ${argv.foo} and bar ${argv.bar}`)
  }
}
```

Note also that if you just want to make sure pairs of options are set together, you can replace the custom check with `.implies()`, like so:

```js
.implies({
  foo: 'bar',
  bar: 'foo'
})
```

HTH!

**Comment by fearphage** [comment]
@nexdrew Thank you! That's very helpful. I'm actually shooting for the opposite effect. 

> You cannot specify both `foo` *and* `bar`. 

Would you use `.check` for that or some other mechanism?

**Comment by nexdrew** [comment]
@fearphage At the moment, I'd use a custom `.check()` for that, so you're right on the money there. If you need special transformation or validation of specific individual options (i.e. dealing with one option at a time), you could use `.coerce()`, but `.check()` was built for this exact purpose of performing custom validation across all parsed options.

Otherwise, the request to support "conflicting" options (as the _opposite_ of `.implies()`) seems to be somewhat popular, see #534. Please feel free to add your ideas/feedback there.

And thanks for using yargs!

**Comment by bcoe** [comment]
this issue was addressed some time ago, with the introduction of a second parameter to `check` which allows you to specify whether or not it is global. If global, the check will apply to the top level and to commands.
