### ISSUE TITLE
Command handler does not get default options

### ISSUE THREAD

**Issue by kumar303** [yargs/yargs#409]
A command handler does not receive an `argv` object with the default options for the program. Is this by design? How would a sub-command be able to work with options that are common to all commands?

To reproduce:
````javascript
var yargs = require('yargs');

var argv = yargs
  .options({
    'some-global': {
      default: 'the default',
    },
  })
  .command('cmd', 'a sub command', function(argv) {
    console.log('[cmd] argv.someGlobal', argv.someGlobal);
  })
  .argv;

console.log('argv.someGlobal', argv.someGlobal);
````

This outputs:
````
$ node script.js cmd
[cmd] argv.someGlobal undefined
argv.someGlobal the default
````
But I'd expect it to output:
````
$ node script.js cmd
[cmd] argv.someGlobal the default
argv.someGlobal the default
````
I'm using `yargs@4.2.0` and node `4.3.0`

**Comment by nexdrew** [comment]
@kumar303 Hey, sorry for the confusion! In 4.x we introduced the concept of "global" options for this purpose. Have you tried adding `global: true` to the outer options (or using `.global('option-key')`)?

**Comment by kumar303** [comment]
Hmm. That didn't do anything. I changed the test script to:
````javascript
var yargs = require('yargs');

var argv = yargs
  .options({
    'some-global': {
      global: true,
      default: 'the default',
    },
  })
  .command('cmd', 'a sub command', function(argv) {
    console.log('[cmd] argv.someGlobal', argv.someGlobal);
  })
  .argv;

console.log('argv.someGlobal', argv.someGlobal);
````
but it's still undefined in the command handler:
````
$ node script.js cmd
[cmd] argv.someGlobal undefined
argv.someGlobal the default
````
Adding `.global('some-global')` also had no effect.

**Comment by nexdrew** [comment]
@kumar303 Ok, sorry, I didn't read your OP well enough on my phone :)

I think the problem is that the optional 3rd and 4th arguments to `.command()` changed in 4.x.

In 3.x, you could provide a single handler function that accepts a `yargs` instance and an `argv` object.

```js
// 3.x
var argv = require('yargs')
  .option('some-global', {
    default: 'the default'
  })
  .command('cmd', 'a sub command', function (yargs, argv) {
    console.log('[cmd] argv.someGlobal', argv.someGlobal)
  })
  .argv
console.log('argv.someGlobal', argv.someGlobal)
```

But the semantics of exactly how you were supposed to use the "inner" yargs instance was always a little confusing. The concept of "global" options did not exist. Typically you would have to redefine all the "global" options again in each command handler, something like `argv = yargs.option('some-global', { default: 'the default' }).argv`.

In 4.x, you can now provide two functions, the first being a builder function that accepts (and returns) a `yargs` instance and the second being a handler function that accepts an `argv` object.

```js
// 4.x
var argv = require('yargs')
  .option('some-global', {
    global: true,
    default: 'the default'
  })
  .command('cmd', 'a sub command', function (yargs) {
    // could add command-specific config here
    // global options are retained
    return yargs
  }, function (argv) {
    // everything's been parsed, so go do something
    console.log('[cmd] argv.someGlobal', argv.someGlobal)
  })
  .argv
console.log('argv.someGlobal', argv.someGlobal)
```

And since "global" options are now a thing, you don't have to redefine them for each command.

In 4.x, you can also provide a module with a `builder` and `handler` function as the 3rd argument, or you can just provide an options object for the 3rd argument (if no special logic is needed beyond configuring options).

I think what you're looking for is something like the 4.x code snippet above. Try that out and let us know what you think.

**Comment by kumar303** [comment]
Aha, thanks, this works as expected with the 4.x example. I actually read about this new signature in the docs but I think what I was missing was the `global = true` part.

**Comment by nexdrew** [comment]
@kumar303 Cool. Ok to close?

**Comment by kumar303** [comment]
yes, thanks for the detailed examples
