### ISSUE TITLE
strict mode error

### ISSUE THREAD

**Issue by Alphapage** [yargs/yargs#472]
Hello,

I'm using yargs 4.4.0 with nodejs 4.2.2.
I can reproduce the bug like this:
```var yargs=require('yargs');``` from test.js file
Then:
```node --use_strict test.js```

I get this error: In strict mode code, functions can only be declared at top level or immediately within another function.

Is it a bug or a limitation ?

Thanks in advance for your help.

**Comment by bcoe** [comment]
@Alphapage had a worthwhile discussion with @sindresorhus here:

https://github.com/kemitchell/spdx-expression-parse.js/issues/9

tldr; it's recommended that folks use `use strict;` rather than running `node --strict_mode`, other developers I respect such as substack have given similar advice:

https://github.com/nodejs/node-v0.x-archive/issues/7479

Having said this, there's a chance this will eventually be fixed in `spdx-expression-parse.js`, so keep an eye out on that repo.
