### ISSUE TITLE
global options are not affected by environment variables when using sub commands

### ISSUE THREAD

**Issue by kumar303** [yargs/yargs#486]
When declaring a sub command that also has its own options, environment variables no longer affect global options. Is my configuration wrong?

````javascript
var argv = require('yargs')
  .env('MY_PROGRAM')
  .options({
    'f': {
      alias: 'fruit-thing',
      type: 'boolean',
      global: true,
    },
  })
  .command('cmd', '', function(yargs) {
    return yargs.options({
      'sub': {
        type: 'boolean',
      }
    });
  })
  .argv
console.log(argv);
````
I would expect this to print `{fruitThing: true}` but it does not:
````
MY_PROGRAM_FRUIT_THING=true node script.js cmd
````
However, if I comment out `yargs.options(...)` in the sub command, it works.

This is only limited to environment variables. The following works as expected:
````
node script.js --fruit-thing cmd
````

**Comment by nexdrew** [comment]
@kumar303 Good find!

I think the problem is that the `envPrefix` is not treated as "global" - in the context of a command, it has been [reset to `undefined`](https://github.com/yargs/yargs/blob/v4.6.0/yargs.js#L116), meaning env vars will be ignored for that command.

To workaround this, you would have to duplicate your `.env('MY_PROGRAM')` config within each command builder.

I could've sworn there was already an issue for this, but I can't find it now. (Perhaps I'm just remembering conversations from other channels.)

I think the correct fix would be to preserve the `envPrefix` for commands, like a global option. Thoughts?

**Comment by kumar303** [comment]
That fix sounds good to me. It seems like it should apply to sub commands by default. I can use the workaround in the meantime, thanks.
