### ISSUE TITLE
Make yargs configuration testable in-process

### ISSUE THREAD

**Issue by kumar303** [yargs/yargs#489]
The way a yargs program behaves relies heavily on its configuration. It is also easy to botch configuration (e.g. when refactoring code) if you are using abstractions to apply the configuration in different places. A common way to solve this is to add automated tests for the behavior you intended to configure. 

However, it is not easy to test a yargs configuration that would result in the program exiting, such as on a usage error. The only way I can think of is to test in a subprocess but that adds *a lot* of expensive I/O overhead.

Here's an example. If you want to make sure your program exits on an unknown option, such as `script.js --unknown`, the fix is to add `strict()` to the configuration:
````javascript
﻿﻿var argv = require('yargs').strict().argv;
````
How could this be tested in-process?

One solution would be to introduce an option that will cause yargs to throw an exception instead of exit the process. That is, one could write an automated test that executed the program more like:
````javascript

function main(yargs) {
  // imagine that this also adds many other options and commands.
  return yargs.strict().argv;
}

// in the test:
var yargs = require('yargs');
var argv = ['--unknown-option'];
var yargsInstance = yargs(argv, {throwExitError: true});
try {
  main(yargsInstance);
} catch (error) {
  // make assertions about the error.
}
````
If it needs to be asynchronous it could be done with a promise.

**Comment by nexdrew** [comment]
@kumar303 This is an interesting suggestion.

Note that you can pretty much do this by passing pseudo arguments to yargs-as-a-function and using a `.fail()` handler to "catch" the parsing/validation error. The following works and is very close to what you have above:

```js
function main (yargs) {
  return yargs.strict().argv
}

var assert = require('assert')
var failCalled = false
var yargs = require('yargs')
yargs('--unknown-option').fail(function (msg, err) {
  failCalled = true
  // assert on msg/err here
  assert.ok(msg)
})

main(yargs)
assert.ok(failCalled)
```

I don't know if that completely satisfies your use-case, but I think it gets pretty close.

Otherwise, I'd be interested to hear ideas on API improvements to make yargs more test-friendly for consumers. I have a feeling that another userland package/module could maybe wrap yargs for more test sugar, but I'm not quite sure what that would look like right now.

**Comment by nexdrew** [comment]
I should also mention that you can configure yargs to **not** exit the process on validation errors by calling `.exitProcess(false)`, which would perhaps be an alternative to providing a custom `.fail()` handler.

**Comment by kumar303** [comment]
Oh! Sorry, I didn't know about either of these methods. They both do what I was looking for so I'll close this out.

**Comment by bcoe** [comment]
@kumar303 thanks :) be liberal with opening issues in the future 👍
