### ISSUE TITLE
.demand() does not work with .parse(argv)

### ISSUE THREAD

**Issue by adius** [yargs/yargs#520]
This works:

```js
#! /usr/bin/env node

console.dir(
  require('yargs')
    .usage('bug')
    .demand(1)
    .argv
)
```

This should work, but doesn't:

```js
#! /usr/bin/env node

console.dir(
  require('yargs')
    .usage('bug')
    .demand(1)
    .parse(process.argv)
)
```

**Comment by bcoe** [comment]
@adius I wouldn't say this is actually a big, this issue is as follows:

By default yargs removes the first two arguments from [`process.argv`](https://github.com/yargs/yargs/blob/master/index.js#L6), which represent the node bin and the script being executed:

```js
[ '/Users/benjamincoe/.nvm/versions/node/v5.1.0/bin/node',
  '/Users/benjamincoe/bcoe/debug-yargs/foo.js' ]
```

If you execute yargs explicitly, it doesn't try to apply this magic (the assumption being you've probably performed some sort of preprocessing on the arguments):

```js
#! /usr/bin/env node

console.dir(
  require('yargs')
    .usage('bug')
    .demand(1)
    .parse(process.argv.slice(2))
```

would give you identical behavior to

```js
#! /usr/bin/env node

console.dir(
  require('yargs')
    .usage('bug')
    .demand(1)
    .argv
)```

**Comment by adius** [comment]
Uff … that's not intuitive at all.
Anyways, it least it should be made crystal clear in the documentation.
http://yargs.js.org/docs/#methods-parseargs does not make this clear right now!
