### ISSUE TITLE
benchmarks \o/

### ISSUE THREAD

**Issue by bcoe** [yargs/yargs#521]
Someone on the [Internetz](https://twitter.com/RijnhardH/status/736199577360031745) complained that yargs is a slow ... you know what, they're probably right we've never made an effort to run many benchmarks (we're getting to the point of maturity where we probably should). 

_Let's run some benchmarks on yargs, comparing it against some other parsers as a baseline:_

- [ ] optimist
- [ ] commander
- [ ] argparse

_Let's fix a few of the glaring performance issues:_

 * I have my suspicions as to where the most likely performance bottlenecks would be (*cough* [cliui](https://github.com/yargs/cliui))

**This work could be pretty fun.**

thoughts, @nexdrew @maxrimue, @lrlna?

**Comment by rijnhard** [comment]
Hi @bcoe thanks for the tweet. 

as promised, heres the benchmarking code I used: https://github.com/rijnhard/node-crappy-benchmarks

**Comment by rijnhard** [comment]
Feel free to point out issues, also I would just like to give you some credit, for taking this approach. My tweets can be intentionally offensive, but I do have a lot of respect for open source maintainers, and yargs is a fantastic library.

**Comment by bcoe** [comment]
@rijnhard no worries, this has actually given me the opportunity to learn a bit more about v8 CPU profiling -- unfortunately I haven't found any of the quick wins I was hoping for so far. I've benchmarked `cliui` at `2795hz`: that's pretty darn fast, and I couldn't find any quick performance tweaks.

I'll move on to profiling some other parts of yargs, since that didn't immediately jump out as the culprit.

**Comment by rijnhard** [comment]
@bcoe i have updated with a bench of argparse. its slightly slower then Commander, but twice as fast as yargs

**Comment by nexdrew** [comment]
Perhaps we should focus on [`yargs-parser`](https://github.com/yargs/yargs-parser) for the moment? There's definitely a lot of looping and RegExp checks in there.

**Comment by shakyShane** [comment]
I switched to yargs for https://github.com/BrowserSync/browser-sync, but am considering switching away again do to these speed issues.

The elephant is in the room is the fact that from a cold boot, yargs requires 95 individual js files/modules just to get running - this should be addressed before anyone spends time reworking loops/regexes

```js
// require yargs, get the require cache, trim cwd
const yargs   = require('yargs');
const path    = require('path');
const keys    = Object.keys(require.cache);
const trimmed = keys.map(key => path.relative(path.join(process.cwd(), 'node_modules'), key));

console.log(trimmed);
```

Produces the following

```json
[
  "../example.js",
  "yargs/index.js",
  "yargs/yargs.js",
  "yargs/node_modules/lodash.assign/index.js",
  "yargs/node_modules/lodash.assign/node_modules/lodash.keys/index.js",
  "yargs/node_modules/lodash.assign/node_modules/lodash.rest/index.js",
  "yargs/lib/command.js",
  "yargs/lib/completion.js",
  "yargs-parser/index.js",
  "yargs-parser/node_modules/lodash.assign/index.js",
  "yargs-parser/node_modules/lodash.assign/node_modules/lodash.keys/index.js",
  "yargs-parser/node_modules/lodash.assign/node_modules/lodash.rest/index.js",
  "yargs-parser/node_modules/camelcase/index.js",
  "yargs-parser/lib/tokenize-arg-string.js",
  "yargs/lib/usage.js",
  "yargs/node_modules/cliui/index.js",
  "yargs/node_modules/string-width/index.js",
  "yargs/node_modules/string-width/node_modules/strip-ansi/index.js",
  "yargs/node_modules/string-width/node_modules/strip-ansi/node_modules/ansi-regex/index.js",
  "yargs/node_modules/string-width/node_modules/code-point-at/index.js",
  "yargs/node_modules/string-width/node_modules/code-point-at/node_modules/number-is-nan/index.js",
  "yargs/node_modules/string-width/node_modules/is-fullwidth-code-point/index.js",
  "yargs/node_modules/string-width/node_modules/is-fullwidth-code-point/node_modules/number-is-nan/index.js",
  "yargs/node_modules/cliui/node_modules/strip-ansi/index.js",
  "yargs/node_modules/cliui/node_modules/strip-ansi/node_modules/ansi-regex/index.js",
  "yargs/node_modules/cliui/node_modules/wrap-ansi/index.js",
  "yargs/node_modules/decamelize/index.js",
  "yargs/node_modules/window-size/index.js",
  "yargs/lib/obj-filter.js",
  "yargs/node_modules/set-blocking/index.js",
  "yargs/lib/validation.js",
  "yargs/node_modules/y18n/index.js",
  "read-pkg-up/index.js",
  "read-pkg-up/node_modules/find-up/index.js",
  "read-pkg-up/node_modules/find-up/node_modules/path-exists/index.js",
  "read-pkg-up/node_modules/find-up/node_modules/pinkie-promise/index.js",
  "read-pkg-up/node_modules/read-pkg/index.js",
  "read-pkg-up/node_modules/read-pkg/node_modules/load-json-file/index.js",
  "read-pkg-up/node_modules/read-pkg/node_modules/load-json-file/node_modules/graceful-fs/graceful-fs.js",
  "read-pkg-up/node_modules/read-pkg/node_modules/load-json-file/node_modules/graceful-fs/polyfills.js",
  "read-pkg-up/node_modules/read-pkg/node_modules/load-json-file/node_modules/graceful-fs/fs.js",
  "read-pkg-up/node_modules/read-pkg/node_modules/load-json-file/node_modules/graceful-fs/legacy-streams.js",
  "read-pkg-up/node_modules/read-pkg/node_modules/load-json-file/node_modules/strip-bom/index.js",
  "read-pkg-up/node_modules/read-pkg/node_modules/load-json-file/node_modules/strip-bom/node_modules/is-utf8/is-utf8.js",
  "read-pkg-up/node_modules/read-pkg/node_modules/load-json-file/node_modules/parse-json/index.js",
  "read-pkg-up/node_modules/read-pkg/node_modules/load-json-file/node_modules/parse-json/node_modules/error-ex/index.js",
  "read-pkg-up/node_modules/read-pkg/node_modules/load-json-file/node_modules/parse-json/node_modules/error-ex/node_modules/is-arrayish/index.js",
  "read-pkg-up/node_modules/read-pkg/node_modules/load-json-file/node_modules/parse-json/vendor/parse.js",
  "read-pkg-up/node_modules/read-pkg/node_modules/load-json-file/node_modules/parse-json/vendor/unicode.js",
  "read-pkg-up/node_modules/read-pkg/node_modules/load-json-file/node_modules/pinkie-promise/index.js",
  "read-pkg-up/node_modules/read-pkg/node_modules/load-json-file/node_modules/pify/index.js",
  "read-pkg-up/node_modules/read-pkg/node_modules/normalize-package-data/lib/normalize.js",
  "read-pkg-up/node_modules/read-pkg/node_modules/normalize-package-data/lib/fixer.js",
  "read-pkg-up/node_modules/read-pkg/node_modules/normalize-package-data/node_modules/semver/semver.js",
  "read-pkg-up/node_modules/read-pkg/node_modules/normalize-package-data/node_modules/validate-npm-package-license/index.js",
  "read-pkg-up/node_modules/read-pkg/node_modules/normalize-package-data/node_modules/validate-npm-package-license/node_modules/spdx-expression-parse/index.js",
  "read-pkg-up/node_modules/read-pkg/node_modules/normalize-package-data/node_modules/validate-npm-package-license/node_modules/spdx-expression-parse/parser.generated.js",
  "read-pkg-up/node_modules/read-pkg/node_modules/normalize-package-data/node_modules/validate-npm-package-license/node_modules/spdx-correct/index.js",
  "read-pkg-up/node_modules/read-pkg/node_modules/normalize-package-data/node_modules/validate-npm-package-license/node_modules/spdx-correct/node_modules/spdx-license-ids/spdx-license-ids.json",
  "read-pkg-up/node_modules/read-pkg/node_modules/normalize-package-data/node_modules/hosted-git-info/index.js",
  "read-pkg-up/node_modules/read-pkg/node_modules/normalize-package-data/node_modules/hosted-git-info/git-host-info.js",
  "read-pkg-up/node_modules/read-pkg/node_modules/normalize-package-data/node_modules/hosted-git-info/git-host.js",
  "read-pkg-up/node_modules/read-pkg/node_modules/normalize-package-data/node_modules/is-builtin-module/index.js",
  "read-pkg-up/node_modules/read-pkg/node_modules/normalize-package-data/node_modules/is-builtin-module/node_modules/builtin-modules/index.js",
  "read-pkg-up/node_modules/read-pkg/node_modules/normalize-package-data/lib/extract_description.js",
  "read-pkg-up/node_modules/read-pkg/node_modules/normalize-package-data/lib/typos.json",
  "read-pkg-up/node_modules/read-pkg/node_modules/normalize-package-data/lib/make_warning.js",
  "read-pkg-up/node_modules/read-pkg/node_modules/normalize-package-data/lib/warning_messages.json",
  "read-pkg-up/node_modules/read-pkg/node_modules/path-type/index.js",
  "read-pkg-up/node_modules/read-pkg/node_modules/path-type/node_modules/graceful-fs/graceful-fs.js",
  "read-pkg-up/node_modules/read-pkg/node_modules/path-type/node_modules/graceful-fs/polyfills.js",
  "read-pkg-up/node_modules/read-pkg/node_modules/path-type/node_modules/graceful-fs/fs.js",
  "read-pkg-up/node_modules/read-pkg/node_modules/path-type/node_modules/graceful-fs/legacy-streams.js",
  "read-pkg-up/node_modules/read-pkg/node_modules/path-type/node_modules/pinkie-promise/index.js",
  "read-pkg-up/node_modules/read-pkg/node_modules/path-type/node_modules/pify/index.js",
  "yargs/node_modules/pkg-conf/index.js",
  "yargs/node_modules/pkg-conf/node_modules/find-up/index.js",
  "yargs/node_modules/pkg-conf/node_modules/find-up/node_modules/path-exists/index.js",
  "yargs/node_modules/pkg-conf/node_modules/find-up/node_modules/pinkie-promise/index.js",
  "yargs/node_modules/pkg-conf/node_modules/load-json-file/index.js",
  "yargs/node_modules/pkg-conf/node_modules/load-json-file/node_modules/graceful-fs/graceful-fs.js",
  "yargs/node_modules/pkg-conf/node_modules/load-json-file/node_modules/graceful-fs/polyfills.js",
  "yargs/node_modules/pkg-conf/node_modules/load-json-file/node_modules/graceful-fs/fs.js",
  "yargs/node_modules/pkg-conf/node_modules/load-json-file/node_modules/graceful-fs/legacy-streams.js",
  "yargs/node_modules/pkg-conf/node_modules/load-json-file/node_modules/strip-bom/index.js",
  "yargs/node_modules/pkg-conf/node_modules/load-json-file/node_modules/strip-bom/node_modules/is-utf8/is-utf8.js",
  "yargs/node_modules/pkg-conf/node_modules/load-json-file/node_modules/parse-json/index.js",
  "yargs/node_modules/pkg-conf/node_modules/load-json-file/node_modules/parse-json/node_modules/error-ex/index.js",
  "yargs/node_modules/pkg-conf/node_modules/load-json-file/node_modules/parse-json/node_modules/error-ex/node_modules/is-arrayish/index.js",
  "yargs/node_modules/pkg-conf/node_modules/load-json-file/node_modules/parse-json/vendor/parse.js",
  "yargs/node_modules/pkg-conf/node_modules/load-json-file/node_modules/parse-json/vendor/unicode.js",
  "yargs/node_modules/pkg-conf/node_modules/load-json-file/node_modules/pinkie-promise/index.js",
  "yargs/node_modules/pkg-conf/node_modules/load-json-file/node_modules/pify/index.js",
  "object-assign/index.js",
  "yargs/node_modules/pkg-conf/node_modules/symbol/index.js",
  "yargs/node_modules/require-main-filename/index.js"
]

```

the only important metric for cli tools is startup time, and this is your largest contributor to that.

**Comment by shakyShane** [comment]
^ to make that clearer.

We're talking about operating on objects/strings/arrays in **very** small numbers - the chances of a 'refactor' giving any perceivable boost in speed are close to impossible, however, removing dependencies and keeping track of exactly how many modules are loaded can give great results 👍

**Comment by bcoe** [comment]
@shakyShane the yargs project has always made an effort to be sparing with top-level dependencies, well at the same time trying to adhere to the spirit of the [small module philosophy](http://substack.net/how_I_write_modules).

The top-level library only has 13 dependencies, and we take the decision to add new dependencies fairly seriously: sticking mostly with modules within the [yargs org](github.com/yargs], or those built by @sindresorhus (who works on many tools in a similar space to yargs).

I think one thing we could do to address your concerns, and would be worthwhile, would be to lazy-load some of the bigger dependencies. Take `read-pkg-up`, as an example, this is only required if you are using yargs' `pkgConf` functionality (which allows you to load configuration from a stanza in the package.json). If we instead lazy-load this dependency, we immediately drop the # of dependencies required to bootstrap down to:

```js
[ '../test.js',
  '../index.js',
  '../yargs.js',
  'lodash.assign/index.js',
  'lodash.assign/node_modules/lodash.keys/index.js',
  'lodash.assign/node_modules/lodash.rest/index.js',
  '../lib/command.js',
  'require-directory/index.js',
  '../lib/completion.js',
  'yargs-parser/index.js',
  'yargs-parser/node_modules/camelcase/index.js',
  'yargs-parser/lib/tokenize-arg-string.js',
  '../lib/usage.js',
  'cliui/index.js',
  'string-width/index.js',
  'string-width/node_modules/strip-ansi/index.js',
  'string-width/node_modules/strip-ansi/node_modules/ansi-regex/index.js',
  'string-width/node_modules/code-point-at/index.js',
  'string-width/node_modules/code-point-at/node_modules/number-is-nan/index.js',
  'string-width/node_modules/is-fullwidth-code-point/index.js',
  'string-width/node_modules/is-fullwidth-code-point/node_modules/number-is-nan/index.js',
  'cliui/node_modules/strip-ansi/index.js',
  'cliui/node_modules/strip-ansi/node_modules/ansi-regex/index.js',
  'cliui/node_modules/wrap-ansi/index.js',
  'decamelize/index.js',
  'window-size/index.js',
  '../lib/obj-filter.js',
  'set-blocking/index.js',
  '../lib/validation.js',
  'y18n/index.js',
  'pkg-conf/index.js',
  'pkg-conf/node_modules/find-up/index.js',
  'pkg-conf/node_modules/find-up/node_modules/path-exists/index.js',
  'pkg-conf/node_modules/find-up/node_modules/pinkie-promise/index.js',
  'pkg-conf/node_modules/load-json-file/index.js',
  'pkg-conf/node_modules/load-json-file/node_modules/graceful-fs/graceful-fs.js',
  'pkg-conf/node_modules/load-json-file/node_modules/graceful-fs/polyfills.js',
  'pkg-conf/node_modules/load-json-file/node_modules/graceful-fs/fs.js',
  'pkg-conf/node_modules/load-json-file/node_modules/graceful-fs/legacy-streams.js',
  'pkg-conf/node_modules/load-json-file/node_modules/strip-bom/index.js',
  'pkg-conf/node_modules/load-json-file/node_modules/strip-bom/node_modules/is-utf8/is-utf8.js',
  'pkg-conf/node_modules/load-json-file/node_modules/parse-json/index.js',
  'pkg-conf/node_modules/load-json-file/node_modules/parse-json/node_modules/error-ex/index.js',
  'pkg-conf/node_modules/load-json-file/node_modules/parse-json/node_modules/error-ex/node_modules/is-arrayish/index.js',
  'pkg-conf/node_modules/load-json-file/node_modules/parse-json/vendor/parse.js',
  'pkg-conf/node_modules/load-json-file/node_modules/parse-json/vendor/unicode.js',
  'pkg-conf/node_modules/load-json-file/node_modules/pinkie-promise/index.js',
  'pkg-conf/node_modules/load-json-file/node_modules/pify/index.js',
  'pkg-conf/node_modules/object-assign/index.js',
  'pkg-conf/node_modules/symbol/index.js',
  'require-main-filename/index.js' ]```

I think there are a few other dependencies where we could take a similar approach.

**Comment by shakyShane** [comment]
sounds great @bcoe.

I completely understand the desire to follow the 'small module philosophy' - but there are some situations where it has to be either ignored or at least monitored closely - 95 modules for a CLI parser would be one such situation I feel.

no-one wants to read-invent the wheel & of course I deeply respect @sindresorhus and all he does for our community, but it's all about context.

**Comment by sindresorhus** [comment]
> The elephant is in the room is the fact that from a cold boot, yargs requires 95 individual js files/modules just to get running - this should be addressed before anyone spends time reworking loops/regexes

This is just guessing though. Provide some real numbers please. I've done this a lot and I know it's not always about the count, sometimes modules do too much work on require time, which can have much more impact. Use https://github.com/Jaguard/time-require to find out which require's take the longest.

What Node.js version are you on? Node.js 6 substantially improved require times. Require times are usually also slower on Windows, because you know, Windows.

**Comment by sindresorhus** [comment]
There are also a bunch of polyfill dependencies in use. When `yargs` eventually requires Node.js 4, these could be dropped:

```
'string-width/node_modules/code-point-at/node_modules/number-is-nan/index.js',
'pkg-conf/node_modules/find-up/node_modules/pinkie-promise/index.js',
'pkg-conf/node_modules/load-json-file/node_modules/pinkie-promise/index.js',
'pkg-conf/node_modules/object-assign/index.js',
'pkg-conf/node_modules/symbol/index.js',
```

I also noticed `strip-ansi` (and `ansi-regex`) is not deduplicated. Either you're not using npm@3 or there's a version mismatch that should be fixed.

**Comment by shakyShane** [comment]
@sindresorhus

> This is just guessing though. Provide some real numbers please.

It was just a high-level observation that reducing the amount file i/o->parse->compile->run from 95 x is going to yield better results than refactoring loops/regexes - that's all I meant.

I'm not suggesting the approach of this module should be changed, only that if people are going to put time into benchmarking/speeding it up, it should be focussed on areas in which it can make an improvement in the 10s of ms.

**Comment by sindresorhus** [comment]
Agreed

**Comment by marneborn** [comment]
Providing some numbers from my system.
I'm using yargs#4.7.1 with node#4.2.1 on Windows.
I'm timing requiring of yargs, adding 100 options, and then getting .argv.

The total run time is 555ms.

The require('yargs')  took 452ms (81%), with 100 files required.
The biggest contributors are:
- read-pkg-up - 196ms (35%)
- usage - 104ms (19%)
  - cliui - 57ms (10%)
- pkg-conf - 66ms (12%)

Adding the 100 options took 4ms.

The .argv getter took 82ms (15%).

Even halving the run time on the .argv getter only improves the overall run time by 41ms.
As others already have said, this isn't worth the effort.

So, as @bcoe suggested, lazy loading read-pkg-up would be a big help to those of us that don't have options in our package.json.

These three modules are required by multiple sub-modules so are loaded multiple times.
* load-json-file (^1.1.0)
* find-up (^1.0.0)
* graceful-fs (^4.1.2, also uses ~1.1.8...)
Making each of these dependencies of yargs would mean that the subsequent requires would come from the cache instead of reloading it from scratch.

Lazy loading cliui, in lib/usage, would help when running the script, but I only notice that yargs is slow when I do --help (my scripts are slow enough to not care). So that's not useful to me.

Allowing for a condition preventing pkg-conf from being loaded would also speed things up (for anyone without yargs stuff in their package.json).

It does seem that a bunch of the stuff that is slow is related to reading the package.json.
Maybe there's a better way to do that?

Here's the full table of all the require times from my time-require thing.

Time [ms] | count | file
--- | --- | -----------------------------
455 | 1 | node_modules\yargs\index.js
431 | 1 | node_modules\yargs\yargs.js
196 | 1 | node_modules\yargs\node_modules\read-pkg-up\index.js
178 | 1 | node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\index.js
104 | 1 | node_modules\yargs\lib\usage.js
80 | 1 | node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\normalize-package-data\lib\normalize.js
73 | 1 | node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\normalize-package-data\lib\fixer.js
66 | 1 | node_modules\yargs\node_modules\pkg-conf\index.js
64 | 1 | node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\load-json-file\index.js
57 | 1 | node_modules\yargs\node_modules\cliui\index.js
47 | 1 | node_modules\yargs\node_modules\pkg-conf\node_modules\load-json-file\index.js
28 | 3 | node_modules\yargs\node_modules\string-width\index.js
28 | 1 | node_modules\yargs\node_modules\window-size\index.js
27 | 1 | node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\path-type\index.js
25 | 1 | node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\load-json-file\node_modules\graceful-fs\graceful-fs.js
22 | 1 | node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\normalize-package-data\node_modules\validate-npm-package-license\index.js
22 | 1 | tty
21 | 1 | node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\load-json-file\node_modules\parse-json\index.js
18 | 1 | node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\normalize-package-data\node_modules\hosted-git-info\index.js
16 | 1 | node_modules\yargs\node_modules\pkg-conf\node_modules\load-json-file\node_modules\parse-json\index.js
15 | 1 | node_modules\yargs\node_modules\pkg-conf\node_modules\load-json-file\node_modules\graceful-fs\graceful-fs.js
15 | 2 | node_modules\yargs\node_modules\lodash.assign\index.js
15 | 1 | node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\path-type\node_modules\graceful-fs\graceful-fs.js
13 | 1 | node_modules\yargs\node_modules\yargs-parser\index.js
12 | 1 | node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\load-json-file\node_modules\graceful-fs\polyfills.js
12 | 1 | node_modules\yargs\node_modules\read-pkg-up\node_modules\find-up\index.js
11 | 1 | node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\normalize-package-data\node_modules\validate-npm-package-license\node_modules\spdx-expression-parse\index.js
10 | 1 | node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\load-json-file\node_modules\parse-json\vendor\parse.js
9 | 2 | url
9 | 2 | node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\load-json-file\node_modules\graceful-fs\fs.js
9 | 1 | node_modules\yargs\node_modules\string-width\node_modules\strip-ansi\index.js
9 | 1 | node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\normalize-package-data\node_modules\validate-npm-package-license\node_modules\spdx-expression-parse\parser.generated.js
8 | 1 | node_modules\yargs\node_modules\pkg-conf\node_modules\find-up\index.js
8 | 1 | node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\normalize-package-data\node_modules\is-builtin-module\index.js
8 | 1 | node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\normalize-package-data\node_modules\semver\semver.js
7 | 1 | node_modules\yargs\node_modules\pkg-conf\node_modules\load-json-file\node_modules\graceful-fs\polyfills.js
7 | 1 | node_modules\yargs\node_modules\cliui\node_modules\wrap-ansi\index.js
6 | 1 | node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\path-type\node_modules\graceful-fs\polyfills.js
6 | 1 | node_modules\yargs\node_modules\pkg-conf\node_modules\load-json-file\node_modules\parse-json\vendor\parse.js
5 | 1 | node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\normalize-package-data\node_modules\is-builtin-module\node_modules\builtin-modules\index.js
5 | 1 | node_modules\yargs\node_modules\pkg-conf\node_modules\load-json-file\node_modules\parse-json\node_modules\error-ex\index.js
5 | 1 | node_modules\yargs\node_modules\cliui\node_modules\strip-ansi\index.js
5 | 2 | node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\normalize-package-data\node_modules\hosted-git-info\git-host-info.js
5 | 1 | node_modules\yargs\node_modules\string-width\node_modules\code-point-at\index.js
5 | 1 | node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\normalize-package-data\node_modules\validate-npm-package-license\node_modules\spdx-correct\index.js
5 | 1 | node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\load-json-file\node_modules\parse-json\node_modules\error-ex\index.js
4 | 1 | node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\normalize-package-data\lib\make_warning.js
4 | 1 | node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\load-json-file\node_modules\strip-bom\index.js
4 | 1 | node_modules\yargs\node_modules\pkg-conf\node_modules\find-up\node_modules\path-exists\index.js
4 | 1 | node_modules\yargs\node_modules\string-width\node_modules\is-fullwidth-code-point\index.js
4 | 1 | node_modules\yargs\node_modules\pkg-conf\node_modules\load-json-file\node_modules\strip-bom\index.js
4 | 1 | node_modules\yargs\node_modules\read-pkg-up\node_modules\find-up\node_modules\path-exists\index.js
3 | 1 | node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\normalize-package-data\node_modules\hosted-git-info\git-host.js
3 | 2 | node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\path-type\node_modules\graceful-fs\fs.js
3 | 1 | node_modules\yargs\node_modules\lodash.assign\node_modules\lodash.keys\index.js
3 | 2 | node_modules\yargs\node_modules\pkg-conf\node_modules\load-json-file\node_modules\graceful-fs\fs.js
2 | 1 | node_modules\yargs\lib\command.js
2 | 1 | node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\load-json-file\node_modules\parse-json\vendor\unicode.js
2 | 1 | node_modules\yargs\node_modules\pkg-conf\node_modules\load-json-file\node_modules\parse-json\node_modules\error-ex\node_modules\is-arrayish\index.js
2 | 2 | node_modules\yargs\node_modules\pkg-conf\node_modules\find-up\node_modules\pinkie-promise\index.js
2 | 1 | node_modules\yargs\node_modules\lodash.assign\node_modules\lodash.rest\index.js
2 | 1 | node_modules\yargs\node_modules\pkg-conf\node_modules\load-json-file\node_modules\parse-json\vendor\unicode.js
2 | 1 | node_modules\yargs\lib\validation.js
2 | 1 | node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\normalize-package-data\lib\typos.json
2 | 1 | node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\path-type\node_modules\graceful-fs\legacy-streams.js
2 | 1 | node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\path-type\node_modules\pify\index.js
2 | 1 | node_modules\yargs\node_modules\y18n\index.js
2 | 1 | node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\load-json-file\node_modules\graceful-fs\legacy-streams.js
1 | 1 | node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\normalize-package-data\lib\extract_description.js
1 | 1 | node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\load-json-file\node_modules\parse-json\node_modules\error-ex\node_modules\is-arrayish\index.js
1 | 1 | node_modules\yargs\node_modules\string-width\node_modules\strip-ansi\node_modules\ansi-regex\index.js
1 | 1 | node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\normalize-package-data\lib\warning_messages.json
1 | 1 | node_modules\yargs\node_modules\string-width\node_modules\code-point-at\node_modules\number-is-nan\index.js
1 | 1 | node_modules\yargs\lib\completion.js
1 | 1 | node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\load-json-file\node_modules\pinkie-promise\index.js
1 | 1 | node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\load-json-file\node_modules\pify\index.js
1 | 2 | node_modules\yargs\node_modules\set-blocking\index.js
1 | 1 | node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\path-type\node_modules\pinkie-promise\index.js
1 | 1 | node_modules\yargs\node_modules\pkg-conf\node_modules\load-json-file\node_modules\pify\index.js
1 | 1 | node_modules\yargs\node_modules\pkg-conf\node_modules\symbol\index.js
1 | 1 | node_modules\yargs\node_modules\yargs-parser\lib\tokenize-arg-string.js
1 | 1 | node_modules\yargs\node_modules\yargs-parser\node_modules\camelcase\index.js
1 | 2 | node_modules\yargs\node_modules\read-pkg-up\node_modules\find-up\node_modules\pinkie-promise\index.js
1 | 1 | node_modules\yargs\node_modules\pkg-conf\node_modules\object-assign\index.js
1 | 1 | node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\normalize-package-data\node_modules\validate-npm-package-license\node_modules\spdx-correct\node_modules\spdx-license-ids\spdx-license-ids.json
1 | 1 | node_modules\yargs\node_modules\pkg-conf\node_modules\load-json-file\node_modules\pinkie-promise\index.js
1 | 1 | node_modules\yargs\node_modules\decamelize\index.js
1 | 1 | node_modules\yargs\node_modules\pkg-conf\node_modules\load-json-file\node_modules\graceful-fs\legacy-streams.js
1 | 3 | node_modules\yargs\lib\obj-filter.js
1 | 1 | node_modules\yargs\node_modules\pkg-conf\node_modules\load-json-file\node_modules\strip-bom\node_modules\is-utf8\is-utf8.js
1 | 1 | node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\load-json-file\node_modules\strip-bom\node_modules\is-utf8\is-utf8.js
1 | 1 | node_modules\yargs\node_modules\string-width\node_modules\is-fullwidth-code-point\node_modules\number-is-nan\index.js
1 | 1 | node_modules\yargs\node_modules\cliui\node_modules\strip-ansi\node_modules\ansi-regex\index.js
1 | 1 | node_modules\yargs\node_modules\require-main-filename\index.js
0 | 1 | assert
0 | 10 | fs
0 | 9 | path
0 | 8 | util
0 | 3 | stream
0 | 3 | constants

**Comment by sindresorhus** [comment]
I think Node.js 6 with npm@3 will give a lot better number, but sure, can't hurt to lazy load `read-pkg-up`, though would be nice to figure out exactly why it's so slow to require. Maybe I should lazy load something there too. Fixing `read-pkg-up` or one of its dependencies would benefit more projects than just `yargs`. Gut feeling is that it's `normalize-package-data` and `graceful-fs` that makes it slow, but haven't done any benchmarking yet.

**Comment by bcoe** [comment]
@marneborn thanks for this analysis. In the short term, for a `4.8.0` release, I recommend that we:

- [ ] lazy load the modules you've identified.
- [ ] consider adding a configuration option that eliminates calling read-pkg-up in some contexts.

I think this discussion has been a great exercise.

**Comment by nexdrew** [comment]
@bcoe I pushed a branch that uses `lazy-req` for `read-pkg-up`. It does help a little, but I think we' should address looking up the parent package.json file once and cache it for all the ways we potentially use it. I think doing so may obviate the need for the `pkg-conf` dependency.

**Comment by bcoe** [comment]
see: https://github.com/yargs/yargs/pull/544

Going forward let's open specific pull requests for any additional performance improvements that we'd like to make.

**Comment by bcoe** [comment]
@marneborn when you have a few moments, mind giving this a spin:

`npm cache clear; npm i yargs@next`

should address some of the bigger culprits you observed in your benchmarks.

**Comment by marneborn** [comment]
Sorry I took a while to get to this.

I don't really see any improvement.

In 4.7.1 it takes 500ms to do the require('yargs') and 88ms to parse the arguments (.argv getter) with a total runtime of 610ms

In 4.8.0-candidate3 210ms for the require (yay!) but 346ms (boo!) for parse the arguments with a total runtime of 576ms.

The reason we don't see a speedup is that the read-pkg-up is still always loaded, just not until parseArgs()->pkgUp() called.

To really see a speed improvement we either need to make it faster to find the package.json or let folks turn off searching for it.

Maybe something like:
```javascript
  var usePkg = true
  self.usePkg = function (use) {
    if (typeof use !== 'boolean') {
      use = true
    }
    usePkg = use
    return self
  }
```

Use that to conditionally call pkgUp
```javascript
  function parseArgs (args, shortCircuit) {
    options.__ = y18n.__
    options.configuration = usePkg && pkgUp()['yargs'] || {}
```

This usage would be:
```javascript
    yargs
      .usePkg(false)
.
.
.
```

This gets my tests runtime down to 311ms (require=217ms + parsing=74ms)

pkgUp is still called in guessVersion and self.pkgConf but these can be avoided without further changes by manually setting the version and not calling pkgConf.

**Comment by rijnhard** [comment]
I'm going to play devils advocate here. 
I get the point is to make the user interface into the library simple, but won't the performance issue just be better solved if the user can specify a full path to a `package.json`?

```javascript
import yargs from 'yargs';

yargs
      .usePkg('../package.json');
// or 
yargs
      .usePkg(require('../package.json'));
```

The only issue that pops to mind is that if you set it statically for the module, then it can be overwritten. 
And if you set it at an instance level it could be too limiting. 

But I'm sure there is a way around that, with some thought.

**Comment by bcoe** [comment]
@rijnhard @marneborn 576ms, for a command line application to display its interface really isn't too painful -- from back in my usability days, it used to be a rule that folks start to notice interface lag around 500ms, it would be nice to get in the sub-500ms range and we're close. I don't, however, want to disable reading the `yargs` stanza for configuration by default, this is an elegant, simple way to give users a lot of parsing flexibility, something that helps yargs sere a much wider variety of users. Having said that:

* I suggest we look at [find-up](https://github.com/sindresorhus/find-up), and see if there are any quick performance wins (CC @sindresorhus).
* With regards to parsing performance, [yargs' parser](https://github.com/yargs/yargs-parser) has been broken out into its own module for just this purpose -- gives you the guts of the parser, without bells and whistles like loading configuration.
*  If we don't have any luck squeezing some additional performance out of `find-up`, I'd be open to introducing a configuration option to stop configuration from loading, .e.g., `disableConfig`., but I'd rather avoid this additional setting, if we can get performance closer to the ... call it ... 300ms range.
