### ISSUE TITLE
.commandDir(dir) does not work when the yargs definition script is `require`-ed from other file

### ISSUE THREAD

**Issue by popkirby** [yargs/yargs#529]
While I'm building a tool with `.commandDir(dir)`, an error occured when I require `lib/cli.js` and execute `bin/tool.js`.

`node lib/cli.js` works properly.

Directory tree:
```
.
├── bin
│   └── tool.js
├── lib
│   ├── cli.js
│   └── commands
│       └── foo.js
└── package.json

```

bin/tool.js:
```
#!/usr/bin/env node
require('../lib/cli.js');
```

lib/cli.js:
```
'use strict';
require('yargs')
.commandDir('commands')
.argv;
```

lib/commands/foo.js:
```
'use strict';
exports.command = 'foo';
exports.describe = 'description';
exports.builder = {};
exports.handler = function (argv) { console.log('foo') };

```

The error message is:
```
fs.js:945
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/Users/popkirby/Documents/yargs-bug/bin/commands'
    at Error (native)
    at Object.fs.readdirSync (fs.js:945:18)
    at requireDirectory (/Users/popkirby/Documents/yargs-bug/node_modules/require-directory/index.js:59:6)
    at Object.self.addDirectory (/Users/popkirby/Documents/yargs-bug/node_modules/yargs/lib/command.js:72:5)
    at Object.Yargs.self.commandDir (/Users/popkirby/Documents/yargs-bug/node_modules/yargs/yargs.js:211:13)
    at Object.<anonymous> (/Users/popkirby/Documents/yargs-bug/lib/cli.js:4:2)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
```

**Comment by nexdrew** [comment]
@popkirby I can confirm this is an issue, thanks for reporting! The problem is that yargs is interpreting a top-level `.commandDir()` call as relative to `require.main.filename`, which in this case is `/Users/popkirby/Documents/yargs-bug/bin/tool.js`. I will need to think about a proper solution.

In the meantime, you can workaround this by using `__dirname`. E.g. change **lib/cli.js** to this:

```js
'use strict';
var join = require('path').join;
require('yargs')
  .commandDir(join(__dirname, 'commands'))
  .argv;
```

**Comment by leesei** [comment]
> `.commandDir()` call as relative to require.main.filename

Does this explain why I got `.commandDir is not a function` in `cli.js` with this `package.json`:
```json
{
  "bin": "./cli.js",
  "main": "index.js",
}
```

**Comment by bcoe** [comment]
@nexdrew @popkirby could you use https://www.npmjs.com/package/find-up to walk up to the appropriate command directory?

**Comment by torfsen** [comment]
@leesei Just run into this, too. I think the problem is that `commandDir` was [added very recently](https://github.com/yargs/yargs/commit/b299dff4dcee2a95528f4e383d998d1a7378967b) and isn't included in the latest version available from npm (4.7.1).

@bcoe It would be really nice if you could add version information to your documentation so that it's easy to tell in which version a function was added. It's also rather confusing that the docs at http://yargs.js.org/docs/ describe the current development version instead of the latest release on npm. That being said, I'm really looking forward to using `commandDir` :wink:

**Comment by popkirby** [comment]
@bcoe @nexdrew https://www.npmjs.com/package/find-up starts walking up from `process.cwd` by default, so I don't think it can get the appropriate command directory without `__dirname`.

It seems we can get the directory path of the caller by using V8 Stack Trace API (http://stackoverflow.com/questions/13227489/how-can-one-get-the-file-path-of-the-caller-function-in-node-js). I will check whether this method will work with `.commandDir()`.

**Comment by nexdrew** [comment]
@popkirby Yes, I think we may want to use Sindre's `caller-path` or similar.

**Comment by bcoe** [comment]
@nexdrew @popkirby what do you think the ideal behavior should be, I don't know that it makes as much sense to walk to a parent directory for `commandDir`, could we just require that someone use `__dirname` and document this?

**Comment by popkirby** [comment]
@bcoe @nexdrew  Requiring `__dirname` looks little magical and depends on `require-directory`. I prefer making `.commands()` (or `.command()`)  and passing an array / hash of modules to it like below:
```js
// cli.js
require('yargs')
  .commands(require('./commands'))
// or hash without index.js:
// .commands(requireDir('./commands'))
  .argv;

// commands/index.js
module.exports = [require('./cmd1'), require('./cmd2')];

// commands/cmd*.js
exports.command = 'foo';
exports.describe = 'description';
exports.builder = {};
exports.handler = function (argv) { console.log('foo') };
```

**Comment by deedubs** [comment]
Having the docs NOT in sync with what is released is a huge PITA. I was pulling my hair out until I searched for `commandDir` in `node_modules/yargs` and came up empty handed...

**Comment by nexdrew** [comment]
@deedubs Yikes, sorry about that! As you have discovered, this is because our docs come straight from master even though we have not yet published master to the registry.

Sorry this has been in limbo for a while now! The yargs maintainers have been busier than usual with other projects, and I think we might need some discussion about my ideas for the command API and how it aligns with our roadmap before we make this "official".

We could potentially cut a `next` release, but I worry about reneging on functionality people are already using in the wild if we decide this was the wrong direction to pursue. 😓 Please bear with us!

**Comment by deedubs** [comment]
@nexdrew No problem. Thanks so much for your work on yargs!

I think the idea of following master with a next tag is a great path forward but agree that we shouldn't go back now.

**Comment by nexdrew** [comment]
I am currently writing up a roadmap proposal for the command API that I will filter through the yargs team and then make public with an issue in this repo. Hopefully that will help us flesh out problems/concerns before I take us too far down the wrong direction.

In the meantime, I will also get some quick opinions on (1) fixing the docs in master and (2) publishing `.commandDir()` as a new `next` release.

**Comment by shlomisas** [comment]
hi, looks like `commandDir` parameter is not published to NPM yet despite the fact it's 4.7.1 (like in GitHub), any idea when it'll be there?

**Comment by bcoe** [comment]
@nexdrew where do we sit on this issue, safe to close when we release `4.8.0`?

**Comment by nexdrew** [comment]
@bcoe So we've addressed the docs problem and published `commandDir()` in the `next` release, but we still need to address [this](https://github.com/yargs/yargs/issues/529#issuecomment-225620823).

I'd like to try a fix using `caller-path`, which I feel is the proper fix, but that's going introduce even more dependencies. Perhaps we can start to lazy-load conditionally used deps?

**Comment by bcoe** [comment]
@nexdrew in https://github.com/yargs/yargs/pull/544 I've addressed some performance concerns by lazy-loading and `read-pkg-up`, and caching the package.json.

If you think that `caller-path` is necessary to see this command work over the finish line, let's pull it in (it look a pretty small chain of dependencies).

**Comment by bcoe** [comment]
@popkirby give this a shot:

`npm cache clear; npm i yargs@next`

@nexdrew has fixed your issues \o/
