### ISSUE TITLE
command should ignore spaces

### ISSUE THREAD

**Issue by hax** [yargs/yargs#540]
Currently extra spaces will be treat as a required positional arguments which is very confuse.

```js
yargs.command('cmd   [arg]')
```

```sh
$ test cmd

Commands:
  cmd   [arg]

Not enough non-option arguments: got 0, need at least 2


$ test cmd a b

{ _: [ 'cmd' ], '$0': '', '': 'b' }
```

**Comment by bcoe** [comment]
👍 sounds like something we should definitely fix.

**Comment by lrlna** [comment]
hey @charlotteis , can we get this tweeted on [YourFirstPr](https://twitter.com/yourfirstpr) ? ✨

**Comment by Charlotteis** [comment]
@lrlna https://twitter.com/yourfirstpr/status/755733795207282688 ✨

**Comment by najamkhn** [comment]
@lrlna @hax on it. :)

**Comment by jmbyerly** [comment]
Hi Yargs-ers! So I think I've fixed the bug, but as a first-time contributor I wanted to check in first before submitting a PR.

When reproducing the bug, I noticed that a similar problem occurs when the user passes in a required positional argument with extra spaces on either side of it: it returns a command with the required argument that was actually passed in the command string and an additional required argument whose value is an empty string for every extra blank space in the command string. 

For the test I wrote to show that the bug is fixed, I used the code snippet given above when the issue was opened, the one without a required positional argument but with an extra space. The bug fix solves both problems but I was wondering if I should write a second test for the related case I described, or if I write one test, which one I should use.

This is actually my first attempted contribution to an OSS project of any kind other than my own, so I figured it was best to play it safe and ask lots of questions. Thanks for the guidance. Love the project!

**Comment by maxrimue** [comment]
Hey @jmbyerly, sounds awesome! I think you can definitely submit your PR with both tests. As you can see, we have _a lot_ of tests in yargs to always make sure everything works as expected in various situations, so it's definitely appreciated if you add more than just one test to the PR, since that increases the number of situations we test for!

Lastly, we don't really care too much about having too many tests like some other folks might do, we actually embrace it. Thanks for looking into this issue!

**Comment by jmbyerly** [comment]
Okay, great! I'll submit a pull request for this tonite then. Thanks!

**Comment by bcoe** [comment]
thanks @jmbyerly!
