### ISSUE TITLE
Bug with default using the .option command

### ISSUE THREAD

**Issue by andrew-w-ross** [yargs/yargs#576]
I changed the example code on the website to this :
```javascript
require('yargs')
    .usage('$0 <cmd> [args]')
    .option('name', {
      alias: 'n',
      describe: 'provide yer name!',
	  default:"default name"
    })
    .command('hello', 'welcome ter yargs!', {}, function (argv) {	  
      console.log('hello', argv.name, 'welcome to yargs!')
    })
    .help('help')
    .argv
```

When running the command with `node example.js name` I was expecting to have the default value 'default name' instead it's undefined. 

I am using version 4.8.1.

**Comment by nexdrew** [comment]
@andrew-w-ross Thanks for reporting! Looks like another out-of-date example in the docs. In order to make the `--name` option (including the default value) apply to the `hello` command, it should be marked as `global: true` (which would apply it to any/all commands) or defined as an option in the command builder (object or function).

Here's a better example:

```js
require('yargs')
  .usage('$0 <cmd> [args]')
  .command('hello [name]', 'welcome ter yargs!', {
    name: {
      default: 'default name'
    }
  }, function (argv) {
      console.log('hello', argv.name, 'welcome to yargs!')
  })
  .help()
  .argv
```

```console
$ node issue576.js hello 
hello default name welcome to yargs!

$ node issue576.js hello andrew
hello andrew welcome to yargs!
```

**Comment by bcoe** [comment]
@andrew-w-ross opened https://github.com/yargs/yargs.github.io/issues/25

**Comment by andrew-w-ross** [comment]
@nexdrew  Thanks a lot.
