### ISSUE TITLE
Proposing format to reconsile the breaking changes in v5.0.0

### ISSUE THREAD

**Issue by osher** [yargs/yargs#628]
Personally I think that this breaking change was a bad decision.
Making the default to be local to the command assumes that the majority of users uses commands, and/or that the majority of options are local to the commands - which I'm not quite sure is true.

Besides - the implementation could have guessed if it's local or default (fka ...global) by the context.

e.g.

```
require('yargs')
.options( { ... default options } )  
.command( 'cmd1', 'descr of cmd1)
.options({ ...options cascading the defaults for cmd1 })
.command( 'cmd2', 'descr of cmd2)
.options({ ...options cascading the defaults for cmd2 })
```

or just

```
require('yargs')
.options( { ... default options } )  
.command( 'cmd1', 'descr of cmd1, { ...options cascading the defaults for cmd1 })
.command( 'cmd2', 'descr of cmd2, { ...options cascading the defaults for cmd2 })
```

Which can then lead to the following, without breaking consistency:

```
require('yargs')
.options( { ... default options } )  
.command( 'cmd1', 'descr of cmd1, { ...options cascading the defaults for cmd1 })
.subcommand('sub11', 'subcommand of cmd 1', { options cascading for subcmd 11 })
.subcommand('sub12', 'subcommand of cmd 1', { options cascading for subcmd 12 })
.command( 'cmd2', 'descr of cmd2, { ...options cascading the defaults for cmd2 })
.subcommand('sub21', 'subcommand of cmd 2', { options cascading for subcmd 21 })
.subcommand('sub22', 'subcommand of cmd 2', { options cascading for subcmd 22 })
```

And then - the next leap is:

```
require('yargs')
.options( { 
   c : {  ... option descripotor for -c/--config },
   ...more option descriptors, and then:
   commands: {
     cmd1 : { //cmd descriptor of cmd1
        alias:        'c',
        describe: 'descr of cmd1', 
        options: { ... option descriptors for cmd1 cascading the defaults ... }
        commands: {
           sub11: { ... cmd descriptor of sub11 cacading cmd1 options that cascade the defaults }
           sub12: { ... cmd descriptor of sub12 cacading cmd1 options that cascade the defaults }
        }
     },
     cmd2: { ... cmd-descriptor of cmd2... }
   }
 } )
```

which can then recurse as many levels as the author might ever need...
Isn't that poetry ? 😃

**Comment by bcoe** [comment]
@nexdrew has done a lot of the heavy lifting for commands, and the way I've seen him using them for some of the applications at npm is really elegant. I'd love to get @nexdrew's feedback on your proposal, I'm sure there might be a good compromise.

I also think part of the problem might simply be one of documentation; I like the current command implementation because it's both very powerful, but very simple -- but perhaps we're not providing enough examples.

One argument I'd put forward, I think it's quite rare that commands would nest more than one level deep.

**Comment by nexdrew** [comment]
Let me attempt to explain things as I see them.

yargs already supports the concept of "cascading" options - top-level options are defined outside of a command definition and command-specific options are defined within a command definition, e.g.

```js
var argv = require('yargs')
  .option('wrap', { // <-- top-level, not cascading
    desc: 'Use --no-wrap to disable wrapping another CLI',
    type: 'boolean',
    default: true
  })
  .command('search <query>', 'Query an endpoint for data', {
    endpoint: { // <-- command-specific
      desc: 'The endpoint to call',
      type: 'string',
      default: '/search'
    }
  }, function (argv) {
    argv._handled = true
    // applies here: argv.url, argv.endpoint, argv.query
    // does not apply here: argv.wrap
  })
  .option('url', { // <-- top-level, cascading
    desc: 'The base url to use for endpoints',
    type: 'string',
    default: 'https://api.example.com',
    global: true
  })
  .argv

if (!argv._handled && argv.wrap) {
  // logic to wrap another CLI
}
```

It's just that options (at any level) must explicitly be marked as `global` in order to "cascade" to lower levels (where levels are defined by the context of a command).

The point is that it only matters _where_ and _how_ your options are defined, not _when_ (in the sense of the order of chained functions).

I don't like an API based on the order of calls, especially when all the calls return the same mutable instance, because it introduces implicit differences based on context and makes the things less idempotent (if that even makes sense).

At any rate, here's what I view as possible solutions that would probably satisfy the most use-cases:

1. Make all options `global` ("cascading") by default
2. Implicitly make options `global` by default if either (a) there are no commands or (b) all commands defined are lacking a builder or handler (what I call "documentation only" commands)

I'm not crazy about number 2 because it reintroduces inconsistency between how commands are handled, and I don't think changing the behavior implicitly makes for a good API.

I could definitely make an argument for number 1, but I'm not sure others feel the same way.

**Comment by bcoe** [comment]
There's an ongoing discussion in Slack, around how we treat options in the context of commands; expect some changes in version 7.x of yargs.
