### ISSUE TITLE
Alias unflagged args like $0 or _

### ISSUE THREAD

**Issue by laggingreflex** [yargs/yargs#630]
Suppose a use case where a command is pretty simple, like:

``` sh
$ linecount file.js
10
```

But there's also an advanced syntax, like:

``` sh
$ linecount file.js --with-diff-from=file2.js
# or
$ linecount -f file.js --with-diff-from=file2.js
```

…with an optional flagged version of the same argument to avoid ambiguity

It would be awesome if both use cases could be configured with alias, like 

``` js
const argv = yargs
  .options({
    file: {
      alias: ['f', '$0']
    }
  })
```

<sub>([backlink](https://github.com/toddbluhm/env-cmd/issues/4#issuecomment-249108601) for personal context)</sub>

**Comment by bcoe** [comment]
@laggingreflex just cleaning up some old issues.

I'm on the fence about adding this feature, it feels a little bit magical (also it hasn't seen any activity in a couple years).

If you want to make a case for this feature, and send a draft PR, I'm open to it, but otherwise I'm closing as inactive for now 👍
