### ISSUE TITLE
camelCasedFlag behavior is bizarre if `.boolean('camel-cased-flag')` is called

### ISSUE THREAD

**Issue by jakub-g** [yargs/yargs#644]
Hi, I was playing with yargs (plain installation) and I noticed this, which seems weird (maybe I'm missing something)
(using yargs@3 and yargs@5, same behavior)

```
$ cat yargs-test.js
var argv = require('yargs').boolean('use-long-names').argv;
console.log(argv);
console.log('useLongNames: ' + !!argv.useLongNames);

$ node yargs-test.js --use-long-names
{ _: [],
  'use-long-names': true,
  useLongNames: [ false, true ],
  '$0': 'yargs-test.js' }
useLongNames: true

$ node yargs-test.js --no-use-long-names
{ _: [],
  'use-long-names': false,
  useLongNames: [ false, false ],
  '$0': 'yargs-test.js' }
useLongNames: true
```

Note that `argv.useLongNames` is an array, and evaluates as boolean, it's always `true`.

Is it a correct behavior?

according to https://github.com/yargs/yargs-parser#camel-case-expansion it should be

```
node example.js --foo-bar
{ _: [], 'foo-bar': true, fooBar: true }
```

**Comment by jakub-g** [comment]
In fact the issue only happens when you use `.boolean('use-long-names')`

**Comment by bcoe** [comment]
@jakub-g this definitely looks weird, mind doing me a favor and opening this issue on [yargs-parser](https://github.com/yargs/yargs-parser). Also, some more clarification for me, have you set the argument to `.boolean` and .`array`? or this happens when it's set to `.boolean`.

Talk to you on `yargs-parser`.
