### ISSUE TITLE
super eager `help` command execution

### ISSUE THREAD

**Issue by zkat** [yargs/yargs#676]
I'm not sure if I'm doing something wrong here, but the `help` command is being executed if the word `help` is anywhere in the arguments text. I'm using it for a Slack app. My parser is configured like so:

```
const parser = require('yargs')
  .usage('Usage: /<command> <args>')
  .commandDir('../commands')
  .demand(1)
  .strict()
  .help()
  .alias('help', 'help?')
  .alias('help', 'h')
```

I expect `help` to run in only two cases: If a user does `/help?` or if they do `/<command> --help`, but not if there's just `/<command> something something help something`, which is currently triggering help text. Am I misconfiguring something or misunderstanding how the help auto command works?

**Comment by nexdrew** [comment]
@zkat This is currently how the _implicit help command_ works, so that args like `/<command> help` and `/help <command>` will display help for `<command>`. The idea is that a user only needs to append `help` (or whatever aliases have been defined for `help`) to whatever command they're trying to run to get help for the command instead of actually running it.

If the implicit help command is getting in your way, or if you want to implement your own `help` command, you can disable it by passing `false` to `.help()`. For example, any of the following would disable the implicit command:

```js
.help(false)
.help('help', false)
.help('help', 'Show help', false)
```

Disabling the implicit command doesn't affect the behavior of the flagged option (e.g. `--help`) or any of its aliases (e.g. `-h`).

If you think we should change how parsing determines the presence of the implicit command, or if there's something we can add to the docs to clarify this, I'm certainly open to suggestions. Otherwise, sorry for the confusion! Let us know what you think. Thanks!

**Comment by zkat** [comment]
That makes sense! Is there a way to manually invoke the command if I want to manually have a help command that only works as the top-level one?

**Comment by nexdrew** [comment]
@zkat Not really. You can use one of the following:

- `yargs.showHelp('log')`
- `yargs.parse('--help')`
- `console.log(yargs.getUsageInstance().help())`

But running one of these within a custom help command would only print help text specific to your custom command, which doesn't include all the top-level commands. My various attempts to hack around this have been unsuccessful.

Other folks have asked a similar question before, so I think it would be a good idea to add something to the API to make it easy to get or print the full top-level help text. This will take a bit of refactoring, but I'll give it some thought.

**Comment by shamansir** [comment]
> Other folks have asked a similar question before, so I think it would be a good idea to add something to the API to make it easy to get or print the full top-level help text

It is indeed an important thing, the previous code with `console.log(yargs.help())` stopped to work, since I use `yargs` together with `gulp`. And the global help is actually one of the major things I why I chose `yargs`.

So before I prepared the huge object describing the options:

```javascript
var yargs = require('yargs').usage(...).command(...)....epilogue(...);
// then I used `argv` to extract user options in different `gulp` commands
var argv = yargs.argv;
// ...
// and, for global help, I used:
gulp.task('help', function() { console.log(yargs.help()); });
```

But, `gulp` is what was running the task and in my case one-options help is not needed, there are truly a lot of options for a command in my case: https://github.com/shamansir/rpd/blob/master/gulpfile.js#L46

So I'll probably rollback to the version when it was working as before.

**Comment by shamansir** [comment]
In my case, `"yargs": ">3.25.0 <4.0.0"` in `package.json` returned everything back to previous behaviour. Seems I've sticked with old version for too long :)
