### ISSUE TITLE
Split yargs README into multiple sections

### ISSUE THREAD

**Issue by onury** [yargs/yargs#694]
Clean up the readme with a TOC, better language and meaningful examples.. 
..and you'll get a **galaxy of stars**!

**Comment by bcoe** [comment]
@onury I think the underlying issue is that yargs has become so feature rich, that the format of a single README file has become intractable.

I would love to split the README.md out into several `.md` files in a docs folder; which we would also render on the website; I would love help doing this.

Mind updating this ticket with a title something like:

`split yargs README into multiple sections`

CC: @maxrimue, @nexdrew, @lrlna

**Comment by onury** [comment]
@bcoe Docs folder is a good idea. 
The title was the irony ; / changed..

**Comment by lrlna** [comment]
++1 to folder structure for docs.

**Comment by maxrimue** [comment]
I agree, yargs' functionality has grown a lot and I think it still will be. Looking at the current structure, there just is no way to cope with that without getting a messy result. So yes, let's go for a new format :+1:

**Comment by bcoe** [comment]
@pedalhead I closed #701 in favor of this catch-all issue, let's work together and figure out how to improve yargs' README!

**Comment by lrlna** [comment]
Okay, I have some ideas about getting this started;

We ought to probably do this in batches, and while we are at it, fix some of our examples that are either outdated or are not clear as we go. 

The main README:
- basic example, but we should rework the one we have [upfront](https://github.com/yargs/yargs#examples) and make it a bit more comprehensive. 
- everything else should be in a table of contents: 
* methods (and probably group those a little bit, commands vs options at the very least)
* parsing tricks (i never scrolled down enough to even know we had those wooooops :/) 
* installation
* contributing

**Comment by gajus** [comment]
> I would love to split the README.md out into several .md files in a docs folder; which we would also render on the website; I would love help doing this.

You can split documentation into multiple files using https://github.com/gajus/gitdown. This can be also used to generate table of contents.

**Comment by lrlna** [comment]
👋 , I went to do some research on how other libraries/projects are doing this; so here are some notes/conclusions/thoughts:

### [Underscore](https://github.com/jashkenas/underscore)
- readme and docs are entirely on underscorejs.org rather than in a repo, which I think works for them as a fairly large project; I think our docs can still be mirrored in both website and the repo.
- the docs themselves are API based; so essentially all the usage examples are pertaining to a particular API endpoint. I do like that, but I still would prefer to have a section (or a `.md`) with several usage examples

### [Express](https://github.com/expressjs/express)
- Main readme has a bunch of tips on what express does / main features and links up to a) installing examples and b) examples in the repo itself; I actually quite like that: tell me what you're all about and then lead me to where I can get information on how I could use this

### [Moment](https://github.com/moment/moment)
- Moment's repo has a direct reference to their changelog (or their v2.0.0) right in the readme, which is interesting, and maybe something we should be considering too? i.e. these are the breaking changes, and just have them in the main readme
- the rest of the docs are on the website, but are done a bit differently. Unlike underscore's method breakdown, Moment breaks it down by usage points, i.e. how you might send a query, get/set methods. I am still more inclined to go with method breakdown though.

### [Node Core](https://github.com/nodejs/node)
- I thought I would also look into this as well. The repo is huge, obviously, but they do breakdown their API docs into separate files. It seems to work (i.e. it's pretty organized and all), but I find that won't work very well for us to have a separate file for individual methods.
- The docs site, however, is pretty much the usual examples given a particular method/API, which is 💯 

### [Choo](https://github.com/yoshuawuyts/choo)
- This isn't like the usual breakdown of methods, nor is this a library; *but* I really enjoy reading through it -- very thorough and definitely makes me feel like I would like to use this at some point. 
- things I like are basically that we should consider: toggleable table of contents :fire:, nice list of main features, why people should use this, FAQ section. 

SOOOO this leads me to: how about I start a WIP PR so we can start fiddling with it a bit ^_^? Might be better that we have something going, and then continue the discussion around this here?

**Comment by onury** [comment]
- Main README could have clean introduction, basic examples, and a link to a documentation address •• 
- The repo could have a docs directory that contains `.md` files, just like @bcoe suggested.
- Markdown files (and maybe JS files if they have JSDoc) could be converted to HTML.
- GitHub pages or any other service could be used for •• HTML documentation.

I have a lib ([Docma](https://github.com/onury/docma)) that can build a SPA from JSDoc, Markdown and HTML files. 

This or any other tool can be used to achieve this..

**Comment by onury** [comment]
@lrlna excellent research BTW 👍

**Comment by bcoe** [comment]
this is finally done!
