### ISSUE TITLE
Accept yargs-parser configuration directly instead of just via package.json

### ISSUE THREAD

**Issue by laggingreflex** [yargs/yargs#720]
The `configuration` object that yargs passes to yargs-parser can only be configured via `package.json`. 

https://github.com/yargs/yargs/blob/3fe9b8fdbd53da8841cc001cffe7f7794100031a/yargs.js#L824-L825
```
options.configuration = pkgUp(cwd)['yargs'] || {}
```

User should be able to pass this configuration directly through yargs, such as:
```
require(yargs)(...).configuration({...})
```

**Comment by bcoe** [comment]
@laggingreflex I think it would confuse the API to have both a `.config()` for configuring your own libraries `configuration()` for configuring yargs' settings.

Out of curiosity, what's your specific use-case, such that you don't want to configure in the `package.json`.

**Comment by laggingreflex** [comment]
https://github.com/laggingreflex/yargs-test-720

**Comment by nexdrew** [comment]
This appears to be a bug [introduced with 556 here](https://github.com/yargs/yargs/pull/556/commits/fb5c4896d916ba6a9c326842200ce646012e5287#diff-6dd17733300c85ca1a41786abcb4a1c9R639). In order to find the package.json file closest to `require.main.filename`, the line in `parseArgs` that calls `pkgUp(cwd)` should be calling `pkgUp()` instead (i.e. should not use `cwd`), which we do in `guessVersion()` [here](https://github.com/yargs/yargs/blob/51af0a640ba3df0f86b9ed1dd01ade018af6b279/yargs.js#L634).

I can confirm the problem and the fix, but applying the fix gives me these test results:
<img width="561" alt="screen shot 2016-12-05 at 10 41 11 am" src="https://cloud.githubusercontent.com/assets/1929625/20891119/70be8422-bad7-11e6-8865-f42d5e2abd56.png">

Thus, I need to look into the test that's supposed to be covering that line in lib/validation.js.

**Comment by bcoe** [comment]
@laggingreflex a fix for this is going out in the next release of yargs; it's a pretty big one and I would love the extra help testing. Here's how you can get a sneak peek:

`npm cache clear; npm i yargs@next`

Let me know if this does the trick for you.

**Comment by bcoe** [comment]
@laggingreflex I confirmed that the latest yargs works with the example `yargs-test-720`; thanks for writing this! it made testing quite easy:

```bash
Benjamins-MBP-2:~ benjamincoe$ yargs-test-720 -x 3 -x 4 -x 99
99
```

**Comment by bennettellis** [comment]
see also https://github.com/yargs/yargs/issues/828
