### ISSUE TITLE
example-text in seperated lines instead two-columns

### ISSUE THREAD

**Issue by xstable** [yargs/yargs#747]
Is it possible in any way to trigger an option which makes the output of .example() each line after the other, instead of two-column lines?

on long example-lines (first parameter) there are a suboptimal posititoning.

**Comment by maxrimue** [comment]
You can use [`.wrap()`](https://github.com/yargs/yargs#wrap) to specify the amount of columns at which lines should break. If you want the interface to be just as wide as your terminal, do:
```javascript
.wrap(process.stdout.columns)
```

Otherwise, use any integer:
```javascript
.wrap(120)
```

Please reopen the issue if you still have questions or concern. Thanks for asking!

**Comment by xstable** [comment]
Ok, this seems not to answer my request
I Asked not to expand the columns, I ask to write first the example, then LineBreak, then the description.
The above wrap()-Command result not in this.
