### ISSUE TITLE
it's weird that running `--help` on default command does not show help for all commands

### ISSUE THREAD

**Issue by bcoe** [yargs/yargs#803]

**Comment by nexdrew** [comment]
Yeah. I think my rationale was that it would be best to display the command-specific help when a default command with no aliases is given, but this seems silly to me now.

To fix this, I think we just need to add the `&& !argv[helpOpt]` condition to [this line here](https://github.com/yargs/yargs/blob/bc564685df4aa45b828f22b813ce567ea0565061/yargs.js#L1014).

Here's an example with before and after results:

```js
require('yargs')
  .command(['one [thing]', 'first'], 'First command', {}, argv => {
    console.log('one:', argv)
  })
  .command(['two', 'second'], 'Second command', {}, argv => {
    console.log('two:', argv)
  })
  .command('three', 'Third command', {}, argv => {
    console.log('three')
  })
  .command('* [uhh]', 'Default command', {}, argv => {
    console.log('default:', argv)
  })
  .help()
  .argv
```

**Before** the change:

```console
$ node defaultcmd.js --help
defaultcmd.js [uhh]

Options:
  --help  Show help                                                    [boolean]
```

**After** the change:

```console
$ node defaultcmd.js --help
Commands:
  one [thing]  First command                                    [aliases: first]
  two          Second command                                  [aliases: second]
  three        Third command

Options:
  --help  Show help                                                    [boolean]
```

The "before" result displays help text specific to the default command; in this example it indicates the optional `uhh` positional arg (which is probably an unlikely scenario) instead of listing the other commands.

The "after" result displays top-level help text (which is probably what we want).

@bcoe Let me know what you think, and I can submit a PR.

**Comment by bcoe** [comment]
@nexdrew this feels better to me; it's nice for a person new to the application to be able to list everything available to them 👍 

I've been experimenting with yargs 7 in slackboard at npm today, really happy so far.
