### ISSUE TITLE
allow to pass yargs-parser config programmatically

### ISSUE THREAD

**Issue by atian25** [yargs/yargs#828]
not only read from package.json, maybe:

`yargs.config({ camel-case-expansion: true}).parse(argv)`

**Comment by bcoe** [comment]
@atian25 this seems like a reasonable request ... I wonder if we could even introduce a new method, e.g., `parserConfig`, with the caveat that I want to (within reason) avoid adding any more documentation into README.md until we refactor our docs into multiple `.md` files 😛

**Comment by atian25** [comment]
BTW, the pkg file you guest at https://github.com/yargs/yargs/blob/master/yargs.js#L490,

plz provide a getter for it~

**Comment by bennettellis** [comment]
we have similar problems with using yargs with mocha tests in and IDE like webstorm.  The problem is that the package.json file that's always found by yargs pkgUp is mocha's package file, not ours. So when we run tests this way, they fail to find their properties because the configuration options we specify for yargs don't get loaded. If we could also pass them in programmatically then we can get the tests to work properly. This used to work with yargs but stopped working correctly some time ago. We've tried using the cwd parameter, but that doesn't seem to work as a result of the fix here: https://github.com/yargs/yargs/issues/720

**Comment by pizzafroide** [comment]
In the meantime, here's a possible workaround:

**yargs-parser-options.js :**
```js
import yargsParser from 'yargs-parser';

const originalParsingFunction = yargsParser.detailed;

export default function setYargsParserConfig(configuration) {
  if (!configuration)
    yargsParser.detailed = originalParsingFunction;
  else
    yargsParser.detailed = args => originalParsingFunction(args, { configuration });
}
```

**test.js**
```js
import yargs from 'yargs';
import setYargsParserConfig from './yargs-parser-options';

setYargsParserConfig({ 'camel-case-expansion': false });
console.log(yargs.parse([ '--camel-case' ]));
// => { _: [], 'camel-case': true,'$0': 'test.js' }

setYargsParserConfig(); // reset default
console.log(yargs.parse([ '--camel-case' ]));
// => { _: [], 'camel-case': true, camelCase: true, '$0': 'test.js' }
```
