### ISSUE TITLE
All capital method names in docs

### ISSUE THREAD

**Issue by ozum** [yargs/yargs#836]
Hi,

Just a reminder, http://yargs.js.org/docs/ has listed all method names in ALL-CAPITAL letters because of the font selected.

![screen shot 2017-03-24 at 13 44 41](https://cloud.githubusercontent.com/assets/1497060/24290960/b0917d4e-108f-11e7-8adb-1bd6d4ed142e.png)

OS: MacOS 10.12.2
Browser: Chrome 56

Kind Regards,

**Comment by bcoe** [comment]
@ozum thanks for the report; mind opening it on https://github.com/yargs/yargs.github.io so that it doesn't get lost in the shuffle ...

A larger topic for discussion, I would like to split the yargs README into multiple documents, and switch the API over to [git-books](https://github.com/GitbookIO/gitbook).

**Comment by ozum** [comment]
Ok, I opened a case at https://github.com/yargs/yargs.github.io/issues/32
