### ISSUE TITLE
Paring string parameter with caret (^) character

### ISSUE THREAD

**Issue by justinneff** [yargs/yargs#860]
When a parsing a string parameter, the value returned removed any caret (^) characters from the value. Below is a simple example the replicates the problem I am having.

**yargs-caret.js**
```js
#!/usr/bin/env node
var argv = require('yargs')
  .string('p')
  .argv

console.log(argv.p)
```

When the called the result that prints out does not contain the caret:
```
$ yargs-caret -p caret^Test
caretTest

$ yargs-caret -p 'caret^Test'
caretTest

$ yargs-caret -p "caret^Test"
caretTest
```

Is this a bug or is there a setting that I am missing?

**Comment by nexdrew** [comment]
@justinneff I'm unable to reproduce this issue, and I'm guessing it's a Windows cmd or batch file problem.

Based on [this SO post](http://stackoverflow.com/questions/5254460/how-can-i-get-a-password-containing-a-caret-passed-unchanged-as-a-parameter) about a similar problem, some folks recommend storing the password in a file and then loading the value from file in your bin; this helps to avoid any munging of Windows escape characters on the command line that might be in the password.

If you think that's a viable workaround, you could possibly use the [`.config()` method](http://yargs.js.org/docs/index.html#methods-configkey-description-parsefn) to treat the command line option as a path to a JSON file which would be automatically loaded and added to `argv` when given.

Otherwise, you might need to find a way to escape the carets before passing the password to your bin.

If you don't think this is a Windows problem, please provide more details, such as:
- shell being used
- version of Node being used
- version of yargs being used (looks like [current master of ims-migration](https://github.com/gatewayapps/ims-migration/blob/8d0e73ed89cc0d1b98a1e3d2e89788daf94cc75d/package.json#L43) uses at least 7.0.2)

Thanks!

**Comment by justinneff** [comment]
@nexdrew it does appear to be Windows problem and it appears other characters besides a caret are impacted. I am not sure which way I am going to address this in my project, but it is definitely not a problem in yargs. 

Since the problem is caused by the way Windows interprets the inputs, I am closing this issue.

Thanks for your help!

**Comment by AgentEnder** [comment]
Not to beat a dead horse, but here is a minimum reproduction that showcases the difference on windows. This is definitely not a yargs problem though.

https://github.com/AgentEnder/command-line-carets/actions/runs/720531417
