### ISSUE TITLE
Unexpected behavior with hyphenated boolean options

### ISSUE THREAD

**Issue by Stephen-Meyerhofer** [yargs/yargs#879]
yargs version: 8.0.1

```js
const argv = require('yargs').options({
  'hyphen-bool': {
    type: 'boolean'
  },
  'no-update': {
    type: 'boolean'
  },
  'o-update': {
    type: 'boolean'
  }
}).argv

console.log( argv )

// $ node index.js --hyphen-bool --no-update --o-update
// { _: [],
//   'hyphen-bool': true,
//   hyphenBool: true,
//   'no-update': false,
//   noUpdate: false,
//   'o-update': true,
//   oUpdate: true,
//   update: false,
//   '$0': 'index.js' }
```

I ran across this surprising behavior. Apparently having "no" before -update causes a separate update argument to be parsed and no-update/noUpdate to be set incorrectly.

I have not yet looked at 1 line of the yargs project or the yargs-parser. I am raising the issue first to see if someone with experienced eyes can explain in less time. Thanks!

**Comment by bcoe** [comment]
@Stephen-Meyerhofer this behavior is somewhat expected, because yargs has special handling of `--no` for boolean arguments.

https://github.com/yargs/yargs-parser#boolean-negation

You can disable this functionality by adding the following to your `package.json`:

```json
{
  "yargs": {
     "boolean-negation": false
  }
}
```

The idea is that when someone specifies `--no-foo` in their CLI, they probably want a variable `foo = false` rather than a variable `noFoo`.

**Comment by Stephen-Meyerhofer** [comment]
I like that idea, and it is human-friendly. Knowing that, I can do the following:

```js
const argv = require('yargs').options({
  update: {
    default: true,
    type: 'boolean'
  }
}).argv

console.log( argv )

// $ node index.js
// { _: [], update: true, '$0': 'index.js' }
// $ node index.js --no-update
// { _: [], update: false, '$0': 'index.js' }
```

**Comment by bcoe** [comment]
@Stephen-Meyerhofer awesome 👍 let me know if you bump into any more issues.
