### ISSUE TITLE
Double quotes displayed with a backslash in help.

### ISSUE THREAD

**Issue by tecfu** [yargs/yargs#884]
Let's say I have the following option definition in yargs:

```js
...
yargs.option('escape',{
	describe:'Set the escape character. One character only.',
	default:'"'
});
```

And then I issue the help command:

```sh
node myapp.js -h
```

I will see the following 

```
--escape            Set the escape character. One character only.
                                                              [default: "\""]
```

I don't want the user to see escaped double quotes. Any ideas on this?

**Comment by angadgill92** [comment]
If you see the source code [`lib/usage.js : line 416`](https://github.com/yargs/yargs/blob/f3f074bd983e9b2dea6df94e21febfeef27b6de4/lib/usage.js#L416), you'll notice that `JSON.stringify` is being applied to the `value` you provide, even if the `typeof value` is `string`, this is being done to add double quotes to the output, since all the code is written in standard-js which disallows double quotes.

**Comment by tecfu** [comment]
Sweet. Thanks for fix.
