### ISSUE TITLE
How print help for all commands from the default command (*) handler?

### ISSUE THREAD

**Issue by moersing** [yargs/yargs#893]
Hi, I have a problem, just use the `yargs.showHelp` Api ,it only print:
 ```
[Options]:  
     -v, --version  show version number 
     ......
```
 But I need all help informations , such as  use `-h` option ,  that can printing `[Usage]` ,`[Command]` and `[Options]`.

Can you give me suggestion?  Thanks.

**Comment by bcoe** [comment]
@moersing could you please provide sample code for what you are running; `showHelp()` should print the exact same output as `-h`.

**Comment by moersing** [comment]
![image](https://user-images.githubusercontent.com/12471233/27018981-2ea85aca-4f67-11e7-903c-6a1ae60b0d1e.png)
see, I used `default command`  with handler function  which executing `showHelp()` method, but print below:  
 
![image](https://user-images.githubusercontent.com/12471233/27020721-1f1fbf3a-4f76-11e7-8c0e-b0cc5f4ba3ac.png)

`-h` option print  below : 
 
![image](https://user-images.githubusercontent.com/12471233/27020754-5da1e102-4f76-11e7-9de4-73e6e1a767de.png)

How do I do ?

**Comment by xxxtonixxx** [comment]
exactly I have the same problem 😢

**Comment by bcoe** [comment]
@xxxtonixxx mind providing a tiny sample repo, or code that I can copy and paste, that reproduces the issue you're seeing?

**Comment by xxxtonixxx** [comment]
Hi @bcoe, here you have your demo https://github.com/xxxtonixxx/yargs-893-demo

I hope this helps you 👍

**Comment by laggingreflex** [comment]
This is by design, I think (@bcoe please correct me if I'm wrong). 

When you use the command syntax, and when you use `showHelp` from *inside* a command (i.e. you've entered `<your-app> example-command` in the CLI), then the `showHelp` would only show help for that particular command (`example-command` in this case). 

So inside the `*` command it only shows help for that command - `*`, and not the other commands. Since `*` doesn't have any child commands, it shows empty (+ the options of course, as they apply to all commands). 

This is similar to how if you had `example-command-1` and `example-command-2` and you were inside the `example-command-1`, `showHelp` would only show help regarding `example-command-1`.

If you want to display all commands in `showHelp` from inside the `*` command, maybe you could add all those commands as *sub commands* inside the `*` handler?

**Comment by xxxtonixxx** [comment]
Hmmm, yes, @laggingreflex, that works, thanks :+1:

However, I would like a better way to do it, cleaner

**Comment by sakulstra** [comment]
I was facing the same issue and @laggingreflex's suggestion worked out :+1:.

Anyways this feels a lot like a workaround and could be handled inside the lib i guess (e.g. add a flag to showHelp or a specialized command for the generic catch case - `showHelpOnInvalidCommand(true)`).
