### ISSUE TITLE
argv alternative

### ISSUE THREAD

**Issue by borela** [yargs/yargs#894]
Is there a method to call instead of the `argv` getter? In cases where the cli always requires a command(and each command has its handler already set), the `argv` called in the entry point will not be used, making the linter complain of unused expression.

A solution would be having a function `run()` or something like that at the end of the Yargs call chain, is there already such function?

Thanks

**Comment by miraage** [comment]
Running main program implicitly by invoking a getter is a side effect.
This is what all developers across the world should avoid.
Please, add an explicit method to run program, e.g. `run()` or `parse()`.

**Comment by LinusU** [comment]
This should probably be closed now, in Yargs 9.0.0 you can call `.parse()` to get the same behaviour as `.argv`, but with a function call instead of a getter 🎉 👏

**Comment by mdevils** [comment]
I was very confused when I was reading documentation with all those lines ending with `.argv` and it was never used. I guessed that I need to do something with the `argv` field value. Took me some time to figure out that side-effect happens when you access `argv` property.

Maybe documentation should be updated with `.parse()` instead of `.argv`?
