### ISSUE TITLE
what's count's meaning in .demand(count, argument, message)?

### ISSUE THREAD

**Issue by MichelleShieh** [yargs/yargs#928]
I am sorry but for some reason I must use the previous version for demand option.

I cannot find any documentation related to the .demand(count, argument, message)
But when I used it with .demand(1, ["f"])
it will keep requesting the argument even though I run something like `$ XXX -f XXX`

I made a try and changed it to .demand(0, ["f"])
and it worked now.

I am wondering what's the meaning for the count here as the first argument?

**Comment by bcoe** [comment]
@MichelleShieh this is the historic demand API, which had about 1,000,000 different types of arguments you could pass to it. I recommend instead using `demandCommand` and `demandOption` (each of which are documented).

These allow you to configure positional arguments and flag arguments separately, rather than having the confusing `demand()` API.

**Comment by shadowspawn** [comment]
An answer was provided, and the old `.demand()` API has been marked as deprecated. Closing this issue.
