### ISSUE TITLE
Alias for positional arguments without command

### ISSUE THREAD

**Issue by laggingreflex** [yargs/yargs#935]
I need the user to input a `root` (dir) either as the 1st positional argument or with the switch `--root`. Is this currently possible? 

It seems currently this is only possible using the [command](https://github.com/yargs/yargs/blob/master/docs/advanced.md#commands) syntax and even then only when using an actual command. 

Currently I'm doing something like `if (!argv.root) argv.root = argv._.shift()` which seems hack*ish*. 

What would be a better solution? Would it help extracting out the part where the `.command()` syntax parses the positional arguments and checks for aliases so that it could also be used in my use case, and if so what could be a good API to use it? I'm not sure how much of a big task this might turn out to be but I could give it a try.

**Comment by bcoe** [comment]
@laggingreflex I think it might be possible to get the behavior you're looking for by using a default command `*`; this command will fire by default at the top level, can have aliases, and can accept positional arguments.

Certainly open to discussing in more detail what an API might look for for the concept of positional non-command arguments. Another topic I'd be interested in addressing, is how to make the command API closer to the option API (allowing more features like `.type()` for a command's positional argument).

**Comment by evocateur** [comment]
I would really like to add type validation for command positional arguments. I'm at a loss when trying to describe (or even indicate) that an optional positional argument has a default, and adding the same key to the `options` makes it output in the flags listing as well...

**Comment by bcoe** [comment]
@evocateur good news, I've been hacking on a solution to this and actually got fairly far while traveling yesterday. My partial solution is to run the positional command variables through yargs-parser. I would love some help seeing this work over the finish line, since it's brought up a few other issues I'd like to address, so is turning into a bigger issue than I'd like.

Perhaps you could open an issue, specific for making positional arguments accept the same configuration settings as flagged options, and I can fill this issue in with some thoughts I have so far.

**Comment by BafS** [comment]
Any new about this problem ?

A good solution may be able to add an alias with an empty string like `.alias('', 'input')` so `./test input.txt` would give `input: 'input.txt'`.
