### ISSUE TITLE
yargs truncating a command line value such as 9.0 -> 9

### ISSUE THREAD

**Issue by shrutijoshi28** [yargs/yargs#938]
Hello,

How do I stop the parsing for an argument being passed such as 9.0.
This gets truncated to 9, which I want to avoid.

Thanks.

**Comment by Morishiri** [comment]
It is happening that way, because it is parsed as number. And 9.0 equals 9.
If you want to receive '9.0' value you may want to set your variable type to string

I've created example yargs call:

    const args = yargs
        .option('number-option', {
            number: true
        })
        .option('string-option', {
            string: true
        })
        .argv;
    console.log(args);

While executed like this:

    node index.js --string-option 9.0 --number-option 9.0

it will give you following output:

    {
         _: [],
        help: false,
        version: false,
        'string-option': '9.0',
        stringOption: '9.0',
        'number-option': 9,
        numberOption: 9,
        '$0': 'index.js' 
    }

So as you may notice, string values are now truncated. Maybe this will help your case.

Regards.
