### ISSUE TITLE
Defining `no-arg` option does not work

### ISSUE THREAD

**Issue by mxl** [yargs/yargs#941]
yargs version: 8.0.2

Running this:

```javascript
console.log(require('yargs')
  .options({
    'no-arg': {
      boolean: true,
      default: false
    }
  }).argv);
```

```bash
$ ./index.js --no-arg

{ _: [],
  'no-arg': false,
  noArg: false,
  arg: false,
  '$0': 'index.js' }
```

but if I use camel case:

```bash
$ ./index.js --noArg

{ _: [], 'no-arg': true, noArg: true, '$0': 'index.js' }
```

I use `--no-arg` with `default: false` instead of `--arg` with `default: true` because I want `--no-arg` to be specified in help.

**Comment by farism** [comment]
Maybe related to https://github.com/yargs/yargs/issues/879 and a few other issues.

You could try disabling the `boolean-negation` option with 

```
{
  "yargs": {
     "boolean-negation": false
  }
}
```

**Comment by bcoe** [comment]
@mxl, as @farism indicates, I believe the underlying issue is that `--no` has special meaning in yargs (representing negation) so you're getting a collision between these two features when setting a default value for `no-arg`.

One option would be instead configuring `arg`:

```js
console.log(require('yargs')
  .options({
    'arg': {
      boolean: true,
      default: true
    }
  }).argv);
```

alternatively, you should be able to use the approach that @farism suggests, disabling negation in the parser.
