### ISSUE TITLE
'version' alias not work anymore.

### ISSUE THREAD

**Issue by ethancfchen** [yargs/yargs#961]
My `yargs` settings:
```
const argv = require('yargs').options({
  v: {
    alias: 'version',
    type: 'string',
  },
  preid: {
    type: 'string',
  },
}).argv;
```

My code:
```
const inputVer = argv.version;
const preid = argv.preid;
console.log(inputVer, preid);
```

Command
```
gulp bump -v prerelease --preid stage
```
It will show `false, 'stage'` in my console.
If I change `alias: 'version'` to `alias: 'bbb'` and my code becomes `const inputVer = argv.bbb;`
With the same command and I got `'prerelease' 'stage'`

Node: v7.10.0
yargs: 9.0.1
yargs-parser: 5.0.0

**Comment by Morishiri** [comment]
Hi,
I did a little digging around the topic and it got changed in version [9.0.0](https://github.com/yargs/yargs/blob/master/CHANGELOG.md#900-2017-09-03). Since then version and help options are enabled by default. 
So while using it as you presented you are aliasing `version` with `v`, not the other way around.
To do what you want in `yargs > 9.0.0` you need to disable `version` option as follows:

```
const argv = require('yargs')
    .version(false)
    .options({
      v: {
        alias: 'version',
        type: 'string',
      },
      preid: {
        type: 'string',
      },
  }).argv;

console.log(argv);
```
and this will work as it worked before I think.

While running (`index.js` contains above listing):
```
$ node index.js -v prerelease --preid stage
```
output is as follows:
```
{ _: [],
  help: false,
  v: 'prerelease',
  version: 'prerelease',
  preid: 'stage',
  '$0': 'index.js' }
```
so I belive that's what you wanted. If no - please let me know. I will try to do some more digging to help you with that :)

**Comment by ethancfchen** [comment]
Oh thanks very much! I think I should read more before I upgrade next time.
Thanks again, you save my time.
