### ISSUE TITLE
NPM Script args can't be forwarded to other scripts any longer?

### ISSUE THREAD

**Issue by brian428** [yargs/yargs#994]
It looks like something changed (in v9 or v10?) related to args forwarded by one NPM script to another script.

I have two simple NPM scripts:
```
"build.prod.aot": "gulp build.prod.aot --color --env-config prod --build-type prod && gulp print.banner",
"build.prod.aot.mock": "npm run build.prod.aot -- --FORCE_MOCK"
```

In the past, I could run `build.prod.aot.mock` and use `yargs.argv` to check whether the `FORCE_MOCK` argument was present. But now, `yargs.argv` does not contain this key.

If I check `process.env.npm_config_argv`, I can see the argument there:
```
{"remain":["--FORCE_MOCK"],"cooked":["run","build.prod.aot","--","--FORCE_MOCK"],"original":["run","build.prod.aot","--","--FORCE_MOCK"]}
```

So while Node/NPM are aware of the argument, it is not found in `yargs.argv`.

I didn't see any mention of this in the changelog, so it _seems_ like a bug? If this is a known change in behavior, please let me know. If it is unexpected, then I can try to create a repro case.

**Comment by brian428** [comment]
Sorry, I should have noted that I'm using Node 8.7, NPM 5.5.1, and Yargs 10.0.3.

**Comment by nexdrew** [comment]
@brian428 Might be worth checking/inspecting/logging `process.argv` just before you use `yargs.argv`.

In my testing, npm just appends the `--FORCE_MOCK` arg to the "forwarded" run script, which, in your example, would be available on `process.argv` for the `gulp print.banner` command (after the `&&`) but not the `gulp build.prod.aot --color --env-config prod --build-type prod` command (before the `&&`). Since yargs reads `process.argv` by default, it won't see the "forwarded" arg when used by the first command/gulp task. I think this would be the case regardless of which version of yargs you use.

To fix your example, you could probably do something like this in your `build.prod.aot` gulp task:

```js
yargs(process.argv.slice(2).concat(JSON.parse(process.env.npm_config_argv).remain)).boolean('FORCE_MOCK').argv
```

Otherwise, you might want to try defining another gulp task that combines `build.prod.aot` and `print.banner` so you don't have to use `&&` in your run script.

**Comment by brian428** [comment]
Aha! Thanks Andrew. I bet this stopped working when I appended the print.banner command (which was fairly recently). It's such an innocuous addition that I would never have thought that was the problem. I'll rework my script to avoid the `&&`.

**Comment by brian428** [comment]
FYI, that was exactly the problem. Thanks again.

**Comment by nexdrew** [comment]
@brian428 No worries, glad you got it sorted out!
